import { randomUUID } from "node:crypto";
import type pg from "pg";
import { AuditRecordV3Schema, assertNoSecretLikeMaterial, authorizeAuditAccess, materializeAuditRecord, verifyAuditChain, type AuditAccessContext, type AuditRecordDraft, type AuditRecordV3, type CompletedSpan } from "@jarvis/audit";

export type AuditQuery={ownerId:string;projectId?:string|null;traceId?:string;correlationId?:string;action?:string;result?:string;limit?:number;afterSequence?:number};
export class PostgresAuditStore{
 constructor(private readonly pool:pg.Pool){}
 private async appendWithClient(client:pg.PoolClient,draft:AuditRecordDraft){
    if(draft.classification==="D5")throw new Error("D5_AUDIT_CONTENT_DENIED"); assertNoSecretLikeMaterial(draft);
    const project=draft.projectId??""; await client.query("SELECT pg_advisory_xact_lock(hashtext($1))",[`audit:${draft.ownerId}:${project}`]);
    const last=await client.query<{stream_sequence:string;record_hash:string}>("SELECT stream_sequence,record_hash FROM audit.records_v3 WHERE owner_id=$1 AND project_id=$2 ORDER BY stream_sequence DESC LIMIT 1",[draft.ownerId,project]);
    const sequence=last.rowCount?Number(last.rows[0]!.stream_sequence)+1:1; const previousHash=last.rowCount?last.rows[0]!.record_hash:null;
    const record=materializeAuditRecord(draft,sequence,new Date().toISOString(),previousHash);
    await client.query("INSERT INTO audit.records_v3(audit_id,audit_version,owner_id,project_id,stream_sequence,action,result,severity,classification,actor_id,actor_type,correlation_id,trace_id,causation_id,occurred_at,recorded_at,previous_hash,record_hash,payload_redacted,retention_class,record) VALUES($1,3,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20)",[record.auditId,record.ownerId,project,record.sequence,record.action,record.result,record.severity,record.classification,record.actor.id,record.actor.type,record.trace.correlationId,record.trace.traceId,record.trace.causationId??null,record.occurredAt,record.recordedAt,record.previousHash,record.recordHash,record.redactions.length>0,record.retentionClass,record]);
    return record;
 }
 async append(draft:AuditRecordDraft){const c=await this.pool.connect();try{await c.query("BEGIN");const r=await this.appendWithClient(c,draft);await c.query("COMMIT");return r;}catch(e){await c.query("ROLLBACK");throw e;}finally{c.release();}}
 async withAuditedTransaction<T>(draft:AuditRecordDraft,mutation:(client:pg.PoolClient)=>Promise<T>){const c=await this.pool.connect();try{await c.query("BEGIN");const value=await mutation(c);const audit=await this.appendWithClient(c,draft);await c.query("COMMIT");return{value,audit};}catch(e){await c.query("ROLLBACK");throw e;}finally{c.release();}}
 async query(context:AuditAccessContext,q:AuditQuery){authorizeAuditAccess(context,q.ownerId,q.projectId??null,"audit.read.self");const limit=Math.min(Math.max(q.limit??100,1),500);const params:unknown[]=[q.ownerId,q.projectId??"",q.afterSequence??0];let sql="SELECT record FROM audit.records_v3 WHERE owner_id=$1 AND project_id=$2 AND stream_sequence>$3";for(const [column,value] of [["trace_id",q.traceId],["correlation_id",q.correlationId],["action",q.action],["result",q.result]] as const){if(value){params.push(value);sql+=` AND ${column}=$${params.length}`;}}params.push(limit);sql+=` ORDER BY stream_sequence ASC LIMIT $${params.length}`;const r=await this.pool.query<{record:unknown}>(sql,params);return r.rows.map(x=>AuditRecordV3Schema.parse(x.record));}
 async verify(context:AuditAccessContext,ownerId:string,projectId:string|null){authorizeAuditAccess(context,ownerId,projectId,"audit.verify");const records=await this.query({...context,capabilities:new Set([...context.capabilities,"audit.read.self"] as const)},{ownerId,projectId,limit:500});return verifyAuditChain(records);}
 async checkpoint(context:AuditAccessContext,ownerId:string,projectId:string|null){authorizeAuditAccess(context,ownerId,projectId,"audit.verify");const records=await this.query({...context,capabilities:new Set([...context.capabilities,"audit.read.self"] as const)},{ownerId,projectId,limit:500});const verification=verifyAuditChain(records);if(!verification.ok||!records.length||!verification.headHash)throw new Error("AUDIT_INTEGRITY_ERROR");const checkpoint={checkpointId:randomUUID(),ownerId,projectId,firstSequence:records[0]!.sequence,lastSequence:records.at(-1)!.sequence,recordCount:records.length,chainHeadHash:verification.headHash,createdAt:new Date().toISOString()};await this.pool.query("INSERT INTO audit.checkpoints(checkpoint_id,owner_id,project_id,first_sequence,last_sequence,record_count,chain_head_hash,created_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8)",[checkpoint.checkpointId,ownerId,projectId??"",checkpoint.firstSequence,checkpoint.lastSequence,checkpoint.recordCount,checkpoint.chainHeadHash,checkpoint.createdAt]);return checkpoint;}
 async export(context:AuditAccessContext,ownerId:string,projectId:string|null){authorizeAuditAccess(context,ownerId,projectId,"audit.export");const records=await this.query({...context,capabilities:new Set([...context.capabilities,"audit.read.self"] as const)},{ownerId,projectId,limit:500});const verification=verifyAuditChain(records);if(!verification.ok)throw new Error("AUDIT_INTEGRITY_ERROR");const manifest={schemaVersion:1,ownerId,projectId,recordCount:records.length,firstSequence:records[0]?.sequence??null,lastSequence:records.at(-1)?.sequence??null,chainHeadHash:verification.headHash,verificationOk:true};const exportId=randomUUID();await this.pool.query("INSERT INTO audit.export_manifests(export_id,owner_id,project_id,requested_by,first_sequence,last_sequence,record_count,chain_head_hash,verification_ok,manifest,created_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,true,$9,now())",[exportId,ownerId,projectId??"",context.ownerId,manifest.firstSequence,manifest.lastSequence,manifest.recordCount,manifest.chainHeadHash,manifest]);return{exportId,manifest,jsonl:records.map(r=>JSON.stringify(r)).join("\n")};}
 async appendSpan(ownerId:string,projectId:string|null,span:CompletedSpan){await this.pool.query("INSERT INTO audit.trace_spans(span_id,trace_id,parent_span_id,owner_id,project_id,category,status,started_at,ended_at,duration_ms,safe_attributes) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)",[span.spanId,span.traceId,span.parentSpanId??null,ownerId,projectId??"",span.category,span.status,span.startedAt,span.endedAt,span.durationMs,span.safeAttributes]);}
}
