import type pg from "pg";
import { EventScheduleSchema, JarvisEventEnvelopeSchema, type EventSchedule, type JarvisEventEnvelope, type EventStorePort, type IngressReceiptPort } from "@jarvis/events";

const eventValues=(e:JarvisEventEnvelope)=>[e.eventId,e.eventType,e.schemaVersion,e.occurredAt,e.receivedAt,e.ownerId,e.projectId??null,e.correlationId,e.causationId??null,e.traceId??null,e.producerId,e.producerType,e.sourceEventId??null,e.subject,JSON.stringify(e.payload),e.payloadClassification,e.privacy,e.sequenceKey??null,e.sequence??null,e.chainDepth,e.replayOf??null,e.replayReason??null];
export class PostgresEventStore implements EventStorePort{
  constructor(private pool:pg.Pool){}
  async accept(e:JarvisEventEnvelope){const event=JarvisEventEnvelopeSchema.parse(e);if(event.payloadClassification==="D5")throw new Error("PRIVACY_DENIED");const client=await this.pool.connect();try{await client.query("BEGIN");const q=await client.query(`INSERT INTO events.event_log(event_id,event_type,schema_version,occurred_at,received_at,owner_id,project_id,correlation_id,causation_id,trace_id,producer_id,producer_type,source_event_id,subject,payload,payload_classification,privacy,sequence_key,sequence_value,chain_depth,replay_of,replay_reason) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15::jsonb,$16,$17,$18,$19,$20,$21,$22) ON CONFLICT DO NOTHING RETURNING event_id`,eventValues(event));if(q.rowCount===0){await client.query("ROLLBACK");return "duplicate" as const;}await client.query(`INSERT INTO events.outbox(event_id) VALUES($1)`,[event.eventId]);await client.query("COMMIT");return "accepted" as const;}catch(e){await client.query("ROLLBACK");throw e;}finally{client.release();}}
  async load(id:string){const r=await this.pool.query(`SELECT * FROM events.event_log WHERE event_id=$1`,[id]);const x=r.rows[0];if(!x)return undefined;return JarvisEventEnvelopeSchema.parse({eventId:x.event_id,eventType:x.event_type,schemaVersion:x.schema_version,occurredAt:new Date(x.occurred_at).toISOString(),receivedAt:new Date(x.received_at).toISOString(),ownerId:x.owner_id,...(x.project_id?{projectId:x.project_id}:{}),correlationId:x.correlation_id,...(x.causation_id?{causationId:x.causation_id}:{}),...(x.trace_id?{traceId:x.trace_id}:{}),producerId:x.producer_id,producerType:x.producer_type,...(x.source_event_id?{sourceEventId:x.source_event_id}:{}),subject:x.subject,payload:x.payload,payloadClassification:x.payload_classification,privacy:x.privacy,...(x.sequence_key?{sequenceKey:x.sequence_key,sequence:Number(x.sequence_value)}:{}),chainDepth:x.chain_depth,...(x.replay_of?{replayOf:x.replay_of,replayReason:x.replay_reason}: {})});}
  async claimInbox(e:string,c:string){const inserted=await this.pool.query(`INSERT INTO events.inbox(event_id,consumer_id,state) VALUES($1,$2,'CLAIMED') ON CONFLICT DO NOTHING RETURNING state`,[e,c]);if(inserted.rowCount)return "claimed" as const;const r=await this.pool.query(`SELECT state FROM events.inbox WHERE event_id=$1 AND consumer_id=$2`,[e,c]);return r.rows[0]?.state==="COMPLETED"?"completed" as const:"busy" as const;}
  async completeInbox(e:string,c:string){await this.pool.query(`UPDATE events.inbox SET state='COMPLETED',completed_at=now() WHERE event_id=$1 AND consumer_id=$2 AND state='CLAIMED'`,[e,c]);}
  async sequence(k:string){const r=await this.pool.query(`SELECT sequence_value FROM events.sequence_checkpoints WHERE owner_id='scoped' AND sequence_key=$1`,[k]);return r.rows[0]?Number(r.rows[0].sequence_value):undefined;}
  async setSequence(k:string,v:number){await this.pool.query(`INSERT INTO events.sequence_checkpoints(owner_id,sequence_key,sequence_value) VALUES('scoped',$1,$2) ON CONFLICT(owner_id,sequence_key) DO UPDATE SET sequence_value=GREATEST(events.sequence_checkpoints.sequence_value,EXCLUDED.sequence_value),updated_at=now()`,[k,v]);}
  async deadLetter(e:JarvisEventEnvelope,c:string,code:string,a:number){await this.pool.query(`INSERT INTO events.dead_letters(event_id,consumer_id,error_code,attempts,safe_metadata) VALUES($1,$2,$3,$4,'{}'::jsonb)`,[e.eventId,c,code,a]);}
  async saveSchedule(input:EventSchedule){const s=EventScheduleSchema.parse(input);if(s.classification==="D5")throw new Error("PRIVACY_DENIED");await this.pool.query(`INSERT INTO events.schedules(schedule_id,owner_id,project_id,event_type,schema_version,subject,payload,classification,privacy,timezone,next_due_at,interval_seconds,enabled,occurrence) VALUES($1,$2,$3,$4,$5,$6,$7::jsonb,$8,$9,$10,$11,$12,$13,$14) ON CONFLICT(schedule_id) DO UPDATE SET project_id=EXCLUDED.project_id,event_type=EXCLUDED.event_type,schema_version=EXCLUDED.schema_version,subject=EXCLUDED.subject,payload=EXCLUDED.payload,classification=EXCLUDED.classification,privacy=EXCLUDED.privacy,timezone=EXCLUDED.timezone,next_due_at=EXCLUDED.next_due_at,interval_seconds=EXCLUDED.interval_seconds,enabled=EXCLUDED.enabled,occurrence=EXCLUDED.occurrence,updated_at=now()`,[s.scheduleId,s.ownerId,s.projectId??null,s.eventType,s.schemaVersion,s.subject,JSON.stringify(s.payload),s.classification,s.privacy,s.timezone,s.nextDueAt,s.intervalSeconds??null,s.enabled,s.occurrence]);}
  async dueSchedules(now:string,limit:number){const r=await this.pool.query(`SELECT * FROM events.schedules WHERE enabled=true AND next_due_at<=$1 ORDER BY next_due_at,schedule_id LIMIT $2`,[now,limit]);return r.rows.map(x=>EventScheduleSchema.parse({scheduleId:x.schedule_id,ownerId:x.owner_id,...(x.project_id?{projectId:x.project_id}:{}),eventType:x.event_type,schemaVersion:x.schema_version,subject:x.subject,payload:x.payload,classification:x.classification,privacy:x.privacy,timezone:x.timezone,nextDueAt:new Date(x.next_due_at).toISOString(),...(x.interval_seconds?{intervalSeconds:x.interval_seconds}:{}),enabled:x.enabled,occurrence:Number(x.occurrence)}));}
  async advanceSchedule(id:string,o:number,next:string,enabled:boolean){const r=await this.pool.query(`UPDATE events.schedules SET occurrence=occurrence+1,next_due_at=$3,enabled=$4,updated_at=now() WHERE schedule_id=$1 AND occurrence=$2 RETURNING schedule_id`,[id,o,next,enabled]);return (r.rowCount??0)>0;}
  async health(){const r=await this.pool.query(`SELECT (SELECT count(*) FROM events.outbox WHERE state<>'PUBLISHED') pending,(SELECT count(*) FROM events.dead_letters) dead_letters,(SELECT count(*) FROM events.schedules WHERE enabled) schedules`);return{pending:Number(r.rows[0].pending),deadLetters:Number(r.rows[0].dead_letters),schedules:Number(r.rows[0].schedules)};}
  async claimOutbox(limit=100){const c=await this.pool.connect();try{await c.query("BEGIN");const r=await c.query(`WITH selected AS (SELECT event_id FROM events.outbox WHERE state='PENDING' AND available_at<=now() ORDER BY available_at,event_id FOR UPDATE SKIP LOCKED LIMIT $1) UPDATE events.outbox o SET state='CLAIMED',claimed_at=now(),attempts=attempts+1 FROM selected s WHERE o.event_id=s.event_id RETURNING o.event_id`,[limit]);await c.query("COMMIT");return r.rows.map(x=>String(x.event_id));}catch(e){await c.query("ROLLBACK");throw e;}finally{c.release();}}
  async markPublished(eventId:string){await this.pool.query(`UPDATE events.outbox SET state='PUBLISHED',published_at=now() WHERE event_id=$1`,[eventId]);}
  async releaseOutbox(eventId:string,code:string,delayMs:number){await this.pool.query(`UPDATE events.outbox SET state='PENDING',available_at=now()+($3::text||' milliseconds')::interval,last_error_code=$2 WHERE event_id=$1`,[eventId,code,delayMs]);}
  async deadLetters(limit=100){const r=await this.pool.query(`SELECT d.dead_letter_id,d.event_id,d.consumer_id,d.error_code,d.attempts,d.created_at,e.owner_id,e.event_type FROM events.dead_letters d JOIN events.event_log e USING(event_id) ORDER BY d.created_at DESC LIMIT $1`,[limit]);return r.rows.map(x=>({deadLetterId:Number(x.dead_letter_id),eventId:String(x.event_id),consumerId:String(x.consumer_id),errorCode:String(x.error_code),attempts:x.attempts,createdAt:new Date(x.created_at).toISOString(),ownerId:String(x.owner_id),eventType:String(x.event_type)}));}
}

export class PostgresIngressReceipts implements IngressReceiptPort{
  constructor(private pool:pg.Pool){}
  async claim(p:string,s:string,n:string|undefined,d:string){try{const r=await this.pool.query(`INSERT INTO events.ingress_receipts(producer_id,source_event_id,nonce,signature_digest) VALUES($1,$2,$3,$4) ON CONFLICT DO NOTHING RETURNING source_event_id`,[p,s,n??null,d]);return r.rowCount?"claimed" as const:"duplicate" as const;}catch(e){throw e;}}
  async bind(p:string,s:string,eventId:string){await this.pool.query(`UPDATE events.ingress_receipts SET event_id=$3 WHERE producer_id=$1 AND source_event_id=$2`,[p,s,eventId]);}
}
