import { createHash } from "node:crypto";
import { AuditRecordV3Schema, type AuditRecordDraft, type AuditRecordV3, type AuditRetentionClass } from "./j09-contracts.js";
const retentionDays:Record<AuditRetentionClass,number>={SECURITY:365,OWNER_ACTIVITY:180,OPERATIONAL:30,EPHEMERAL_TRACE:7};
export function canonicalize(value:unknown):string {if(value===null||typeof value==="string"||typeof value==="boolean")return JSON.stringify(value);if(typeof value==="number"){if(!Number.isFinite(value))throw new Error("NON_FINITE_CANONICAL_NUMBER");return JSON.stringify(value);}if(Array.isArray(value))return`[${value.map(canonicalize).join(",")}]`;if(typeof value==="object"){const obj=value as Record<string,unknown>,keys=Object.keys(obj).filter(k=>obj[k]!==undefined).sort();return`{${keys.map(k=>`${JSON.stringify(k)}:${canonicalize(obj[k])}`).join(",")}}`;}throw new Error("UNSUPPORTED_CANONICAL_VALUE");}
export const sha256=(value:string)=>createHash("sha256").update(value).digest("hex");
export function retentionDeadline(recordedAt:string,retentionClass:AuditRetentionClass){const at=Date.parse(recordedAt);if(!Number.isFinite(at))throw new Error("INVALID_RECORDED_AT");return new Date(at+retentionDays[retentionClass]*86400000).toISOString();}
export function materializeAuditRecord(draft:AuditRecordDraft,sequence:number,recordedAt:string,previousHash:string|null):AuditRecordV3{const base={version:3 as const,...draft,sequence,recordedAt,retentionUntil:retentionDeadline(recordedAt,draft.retentionClass),previousHash};const recordHash=sha256(canonicalize(base)+(previousHash??"GENESIS"));return AuditRecordV3Schema.parse({...base,recordHash});}
export type IntegrityAnchor={previousHash:string|null;previousSequence:number};export type IntegrityResult={ok:boolean;checked:number;headHash:string|null;lastSequence:number;reason?:string};
export function verifyAuditChain(input:AuditRecordV3[],anchor:IntegrityAnchor={previousHash:null,previousSequence:0}):IntegrityResult{let previous=anchor.previousHash,expectedSequence=anchor.previousSequence+1;for(const raw of input){const r=AuditRecordV3Schema.parse(raw);if(r.sequence!==expectedSequence)return{ok:false,checked:expectedSequence-(anchor.previousSequence+1),headHash:previous,lastSequence:expectedSequence-1,reason:"SEQUENCE_GAP"};if(r.previousHash!==previous)return{ok:false,checked:r.sequence-(anchor.previousSequence+1),headHash:previous,lastSequence:r.sequence-1,reason:"PREVIOUS_HASH_MISMATCH"};const{recordHash,...base}=r,expected=sha256(canonicalize(base)+(r.previousHash??"GENESIS"));if(recordHash!==expected)return{ok:false,checked:r.sequence-(anchor.previousSequence+1),headHash:previous,lastSequence:r.sequence-1,reason:"RECORD_HASH_MISMATCH"};previous=recordHash;expectedSequence++;}return{ok:true,checked:input.length,headHash:previous,lastSequence:expectedSequence-1};}
export function stackFingerprint(error:unknown){if(!(error instanceof Error)||!error.stack)return null;return sha256(error.stack.replace(/:\d+:\d+/g,":#:##"));}
