import { randomUUID } from "node:crypto";import { appendFile,mkdir } from "node:fs/promises";import { dirname } from "node:path";import { z } from "zod";import { assertNoSecretLikeMaterial,safeText,sanitizeMetadata } from "./j09-redaction.js";import { TraceContextSchema } from "./j09-contracts.js";
export const ErrorCodeSchema=z.enum(["VALIDATION_ERROR","AUTHENTICATION_ERROR","AUTHORIZATION_DENIED","PRIVACY_DENIED","APPROVAL_REQUIRED","TIMEOUT","CANCELLED","DEPENDENCY_UNAVAILABLE","RATE_LIMITED","TOOL_FAILED","VERIFICATION_FAILED","UNKNOWN_OUTCOME","DATA_INTEGRITY_ERROR","AUDIT_INTEGRITY_ERROR","INTERNAL_ERROR"]);export const HealthStatusSchema=z.enum(["HEALTHY","DEGRADED","UNAVAILABLE","STARTING","STOPPING","UNKNOWN"]);export type HealthStatus=z.infer<typeof HealthStatusSchema>;export type DependencyHealth={name:string;status:HealthStatus;reason?:string};
export function healthSnapshot(dependencies:DependencyHealth[],securityLockdown=false){const unavailable=dependencies.some(d=>d.status==="UNAVAILABLE"),degraded=dependencies.some(d=>d.status==="DEGRADED"||d.status==="UNKNOWN");return{liveness:"HEALTHY" as const,readiness:securityLockdown||unavailable?"UNAVAILABLE" as const:degraded?"DEGRADED" as const:"HEALTHY" as const,dependencies};}
export type SafeError={code:z.infer<typeof ErrorCodeSchema>;subsystem:string;message:string;cause?:SafeError;traceId?:string;correlationId?:string};export function safeError(code:z.infer<typeof ErrorCodeSchema>,subsystem:string,message:string,cause?:SafeError):SafeError{return{code,subsystem:safeText(subsystem,64),message:safeText(message,256),...(cause?{cause}:{})};}
export type LogLevel="TRACE"|"DEBUG"|"INFO"|"WARN"|"ERROR"|"FATAL";export function structuredLog(level:LogLevel,service:string,action:string,metadata:Record<string,unknown>,traceId?:string){const safe=sanitizeMetadata(metadata,"D0");return{timestamp:new Date().toISOString(),level,service:safeText(service,64),action:safeText(action,128),...(traceId?{traceId}:{}),metadata:safe.metadata,redactions:safe.redactions};}
export const CompletedSpanSchema=z.strictObject({traceId:z.string().min(1).max(256),spanId:z.string().min(1).max(256),parentSpanId:z.string().min(1).max(256).optional(),correlationId:z.string().min(1).max(256),causationId:z.string().min(1).max(256).optional(),category:z.string().min(1).max(64),status:z.enum(["OK","ERROR"]),startedAt:z.iso.datetime(),endedAt:z.iso.datetime(),durationMs:z.number().finite().nonnegative(),safeAttributes:z.record(z.string().max(64),z.union([z.string().max(256),z.number().finite(),z.boolean(),z.null()])).refine(v=>Object.keys(v).length<=32,"SPAN_ATTRIBUTE_LIMIT")});
export type CompletedSpan=z.infer<typeof CompletedSpanSchema>;
export function completeSpan(trace:unknown,category:string,startedAt:number,status:"OK"|"ERROR",attrs:Record<string,unknown>={}):CompletedSpan{const t=TraceContextSchema.parse(trace),ended=Date.now(),safe=sanitizeMetadata(attrs,"D0");return CompletedSpanSchema.parse({traceId:t.traceId,spanId:t.spanId,...(t.parentSpanId?{parentSpanId:t.parentSpanId}:{}),correlationId:t.correlationId,...(t.causationId?{causationId:t.causationId}:{}),category:safeText(category,64),status,startedAt:new Date(startedAt).toISOString(),endedAt:new Date(ended).toISOString(),durationMs:Math.max(0,ended-startedAt),safeAttributes:safe.metadata});}
export function newTrace(correlationId:string,causationId?:string){return TraceContextSchema.parse({traceId:randomUUID(),spanId:randomUUID(),correlationId,...(causationId?{causationId}:{})});}
export interface TelemetryExporter{export(batch:readonly unknown[]):Promise<void>;close?():Promise<void>}export class NoopTelemetryExporter implements TelemetryExporter{async export(_batch:readonly unknown[]) {}}export class InMemoryTelemetryExporter implements TelemetryExporter{readonly batches:unknown[][]=[];constructor(private readonly maxBatches=100){}async export(batch:readonly unknown[]){if(this.batches.length>=this.maxBatches)this.batches.shift();this.batches.push([...batch]);}}
export class StructuredLocalTelemetryExporter implements TelemetryExporter{constructor(private readonly file:string,private readonly maxBatchBytes=262144){}async export(batch:readonly unknown[]){assertNoSecretLikeMaterial(batch);const lines=batch.map(v=>JSON.stringify(v));const payload=lines.join("\n")+(lines.length?"\n":"");if(Buffer.byteLength(payload)>this.maxBatchBytes)throw new Error("TELEMETRY_BATCH_TOO_LARGE");await mkdir(dirname(this.file),{recursive:true,mode:0o700});await appendFile(this.file,payload,{encoding:"utf8",mode:0o600});}}
export class BoundedTelemetryBuffer{private readonly queue:unknown[]=[];constructor(private readonly exporter:TelemetryExporter,private readonly maxItems=1000,private readonly batchSize=100){}enqueue(item:unknown){if(this.queue.length>=this.maxItems)return false;this.queue.push(item);return true;}get size(){return this.queue.length;}async flush(){const batch=this.queue.splice(0,this.batchSize);if(!batch.length)return;try{await this.exporter.export(batch);}catch{this.queue.unshift(...batch.slice(-Math.max(0,this.maxItems-this.queue.length)));}}}
const allowedLabels=new Set(["subsystem","operation","result","status","provider_class","tool_class","event_type","risk","classification"]);export class MetricsRegistry{private readonly counters=new Map<string,number>();private readonly histograms=new Map<string,number[]>();constructor(private readonly maxSeries=500){}private key(name:string,labels:Record<string,string>){for(const[k,v]of Object.entries(labels)){if(!allowedLabels.has(k)||v.length>64||/@|https?:|[0-9a-f]{24,}/i.test(v))throw new Error("UNBOUNDED_METRIC_LABEL");}const key=name+JSON.stringify(Object.entries(labels).sort());if(!this.counters.has(key)&&!this.histograms.has(key)&&this.counters.size+this.histograms.size>=this.maxSeries)throw new Error("METRIC_SERIES_LIMIT");return key;}inc(name:string,labels:Record<string,string>={},by=1){const k=this.key(name,labels);this.counters.set(k,(this.counters.get(k)??0)+by);}observe(name:string,value:number,labels:Record<string,string>={}){if(!Number.isFinite(value)||value<0)throw new Error("INVALID_METRIC_VALUE");const k=this.key(name,labels),a=this.histograms.get(k)??[];if(a.length<2048)a.push(value);this.histograms.set(k,a);}snapshot(){return{counters:Object.fromEntries(this.counters),histograms:Object.fromEntries([...this.histograms].map(([k,v])=>[k,{count:v.length,min:v.length?Math.min(...v):0,max:v.length?Math.max(...v):0,p50:percentile(v,.5),p95:percentile(v,.95)}]))};}}function percentile(values:number[],p:number){if(!values.length)return 0;const a=[...values].sort((x,y)=>x-y);return a[Math.min(a.length-1,Math.floor((a.length-1)*p))]!;}
export class CostObservability{constructor(private readonly metrics:MetricsRegistry){}model(kind:"estimated"|"actual",minor:number,providerClass:string){this.metrics.observe(`model_cost_${kind}_minor`,minor,{subsystem:"models",provider_class:providerClass});}tool(kind:"estimated"|"actual",minor:number,toolClass:string){this.metrics.observe(`tool_cost_${kind}_minor`,minor,{subsystem:"tools",tool_class:toolClass});}}
