import { afterAll,beforeAll,describe,expect,it } from "vitest";
import { randomUUID } from "node:crypto";
import { homedir } from "node:os";
import { resolve } from "node:path";
import { loadConfig } from "@jarvis/config";
import { FileSecretManager } from "@jarvis/security";
import { databasePool,PostgresEventRetentionRepository,PostgresEventStore,PostgresEventSubscriptionRepository,type DatabasePool } from "@jarvis/storage";
import { MemoryEventTransport,OutboxDispatcher,type JarvisEventEnvelope } from "@jarvis/events";

let pool:DatabasePool;const config=await loadConfig("config/development.json"),owner="j08-owner-"+randomUUID();
const event=():JarvisEventEnvelope=>({eventId:randomUUID(),eventType:"system.integration",schemaVersion:1,occurredAt:new Date().toISOString(),receivedAt:new Date().toISOString(),ownerId:owner,projectId:"jarvis",correlationId:"j08-integration",producerId:"j08-test",producerType:"SYSTEM",subject:"integration",payload:{reference:"safe"},payloadClassification:"D1",privacy:"private-cloud",chainDepth:0});
beforeAll(async()=>{const actor={version:1 as const,id:"j08-integration",kind:"service" as const,environment:"development" as const},manager=new FileSecretManager(process.env.JARVIS_VAULT_FILE??".jarvis/development/vault.json",process.env.JARVIS_MASTER_KEY_FILE??resolve(homedir(),".config/jarvis/typescript/development/master.key"),"development",actor.id,new Set([config.storage.postgres.passwordRef])),lease=await manager.lease(config.storage.postgres.passwordRef,actor);pool=databasePool(config.storage.postgres,lease.value.toString("utf8"));lease.destroy();await pool.query("SELECT 1");});
afterAll(async()=>{if(pool){await pool.query(`DELETE FROM events.subscriptions WHERE owner_id=$1`,[owner]);await pool.query(`DELETE FROM events.schedules WHERE owner_id=$1`,[owner]);await pool.query(`DELETE FROM events.event_log WHERE owner_id=$1`,[owner]);await pool.end();}});
describe("J0.8 PostgreSQL durability",()=>{
 it("J0.8-C — Durable transactional outbox",async()=>{const store=new PostgresEventStore(pool),e=event();expect(await store.accept(e)).toBe("accepted");const r=await pool.query(`SELECT e.event_id,o.state FROM events.event_log e JOIN events.outbox o USING(event_id) WHERE e.event_id=$1`,[e.eventId]);expect(r.rowCount).toBe(1);expect(r.rows[0].state).toBe("PENDING");expect(await store.accept(e)).toBe("duplicate");const count=await pool.query(`SELECT count(*) n FROM events.outbox WHERE event_id=$1`,[e.eventId]);expect(Number(count.rows[0].n)).toBe(1);});
 it("J0.8-R — Outage and crash recovery",async()=>{const store=new PostgresEventStore(pool),e=event();await store.accept(e);const transport=new MemoryEventTransport();transport.available=false;const dispatcher=new OutboxDispatcher(store,transport,0);expect((await dispatcher.dispatch()).released).toBeGreaterThanOrEqual(1);transport.available=true;expect((await dispatcher.dispatch()).published).toBeGreaterThanOrEqual(1);expect(transport.published.some(v=>v.eventId===e.eventId)).toBe(true);expect(await store.claimInbox(e.eventId,"consumer")).toBe("claimed");await store.completeInbox(e.eventId,"consumer");expect(await store.claimInbox(e.eventId,"consumer")).toBe("completed");});
 it("reclaims stale dispatcher and consumer claims after simulated crashes",async()=>{const store=new PostgresEventStore(pool),e=event();await store.accept(e);expect(await store.claimOutbox(1)).toContain(e.eventId);await pool.query(`UPDATE events.outbox SET claimed_at=now()-interval '31 seconds' WHERE event_id=$1`,[e.eventId]);expect(await store.claimOutbox(10)).toContain(e.eventId);await store.releaseOutbox(e.eventId,"SIMULATED_CRASH",0);expect(await store.claimInbox(e.eventId,"crash-consumer")).toBe("claimed");expect(await store.claimInbox(e.eventId,"crash-consumer")).toBe("busy");await pool.query(`UPDATE events.inbox SET claimed_at=now()-interval '31 seconds' WHERE event_id=$1 AND consumer_id='crash-consumer'`,[e.eventId]);expect(await store.claimInbox(e.eventId,"crash-consumer")).toBe("claimed");await store.completeInbox(e.eventId,"crash-consumer");expect(await store.claimInbox(e.eventId,"crash-consumer")).toBe("completed");});
 it("persists owner-scoped subscriptions without cross-owner mutation",async()=>{const repo=new PostgresEventSubscriptionRepository(pool),id="sub-"+randomUUID();await repo.save({subscriptionId:id,consumerId:"consumer",consumerType:"SERVICE",eventType:"system.integration",ownerId:owner,projectId:"jarvis",boundary:"LOCAL",maxClassification:"D4",enabled:true,maxAttempts:3,baseBackoffMs:5,ordered:false,deadLetter:true});expect((await repo.list(owner)).some(v=>v.subscriptionId===id)).toBe(true);expect(await repo.setEnabled("other-owner",id,false)).toBe(false);expect(await repo.setEnabled(owner,id,false)).toBe(true);});
 it("redacts expired private event payload while retaining minimal evidence",async()=>{const store=new PostgresEventStore(pool),retention=new PostgresEventRetentionRepository(pool),e=event();await store.accept(e);await retention.setRetention(owner,e.eventId,"2026-01-01T00:00:00.000Z");expect(await retention.redactExpired(new Date().toISOString(),10)).toContain(e.eventId);const row=await pool.query(`SELECT payload,subject,payload_redacted_at FROM events.event_log WHERE event_id=$1`,[e.eventId]);expect(row.rows[0].payload).toEqual({});expect(row.rows[0].subject).toBe("[redacted]");expect(row.rows[0].payload_redacted_at).toBeTruthy();});
});
