import { afterAll,beforeAll,describe,expect,it } from "vitest";
import { randomUUID } from "node:crypto";
import { homedir } from "node:os";
import { resolve } from "node:path";
import { loadConfig } from "@jarvis/config";
import { FileSecretManager,type AuthorizationV3 } from "@jarvis/security";
import { databasePool,materializeRecoveryManifest,RecoveryControlPlane,PostgresIsolatedRestore,type DatabasePool,J10_BASELINE } from "@jarvis/storage";

let pool:DatabasePool;const config=await loadConfig("config/development.json"),owner="j10-owner-"+randomUUID(),hash="a".repeat(64),now=1_800_000_000_000;
const auth=(capability:string)=>({id:"auth-"+randomUUID(),ownerId:owner,capability,approvalId:"approval-"+randomUUID(),assurance:"A3"}) as unknown as AuthorizationV3;
const manifest=()=>materializeRecoveryManifest({version:2,id:randomUUID(),ownerId:owner,projectId:"jarvis",sourceInstallationId:"install-j10",sourceCommit:J10_BASELINE,createdAt:now,expiresAt:now+86400000,schemaVersion:14,schemaHash:hash,storageVersion:2,encryptionVersion:1,vectorVersion:1,auditVersion:3,eventVersion:1,backupId:randomUUID(),backupType:"FULL",parentBackupId:null,components:[{name:"identity",digest:hash,count:1,required:true},{name:"audit",digest:hash,count:1,required:true}],auditCheckpoint:{sequence:1,hash},keyReferences:["backup-key1"],vaultReferences:[],tombstoneCount:1,deletionObligationCount:1,secretsIncluded:false});
const audit={append:async()=>{}};
beforeAll(async()=>{const actor={version:1 as const,id:"j10-integration",kind:"service" as const,environment:"development" as const},manager=new FileSecretManager(process.env.JARVIS_VAULT_FILE??".jarvis/development/vault.json",process.env.JARVIS_MASTER_KEY_FILE??resolve(homedir(),".config/jarvis/typescript/development/master.key"),"development",actor.id,new Set([config.storage.postgres.migratorPasswordRef])),lease=await manager.lease(config.storage.postgres.migratorPasswordRef,actor);pool=databasePool(config.storage.postgres,lease.value.toString("utf8"),true);lease.destroy();await pool.query("SELECT 1");});
afterAll(async()=>{if(pool)await pool.end();});

describe("J0.10 PostgreSQL recovery sovereignty",()=>{
 it("J0.10-C — Encrypted backup integrity and authenticity",async()=>{const cp=new RecoveryControlPlane(pool,{revalidate:async()=>{}},{verify:async()=>{},activate:async()=>{}},audit,()=>now),m=manifest();await cp.persistManifest(auth("storage.backup.create"),m);const row=await pool.query("SELECT manifest_digest,payload,status FROM recovery.manifests WHERE id=$1 AND owner_id=$2",[m.id,owner]);expect(row.rows[0].manifest_digest).toBe(m.manifestDigest);expect(row.rows[0].status).toBe("VALID");expect(JSON.stringify(row.rows[0].payload)).not.toContain("password");await expect(cp.persistManifest(auth("storage.backup.create"),{...m,manifestDigest:"b".repeat(64)})).rejects.toThrow("RECOVERY_MANIFEST_TAMPERED");});
 it("J0.10-G — Isolated restore only",async()=>{expect(()=>new PostgresIsolatedRestore("jarvis_development",pool,{} as never,{} as never,async()=>{})).toThrow("RESTORE_TARGET_NOT_ISOLATED");const cp=new RecoveryControlPlane(pool,{revalidate:async()=>{}},{verify:async(target)=>{expect(target).toMatch(/^jarvis_restore_test_/);},activate:async()=>{}},audit,()=>now),m=manifest(),p=await cp.createPlan(auth("storage.backup.restore"),m,"jarvis_restore_test_0123456789abcdef",7);await pool.query("UPDATE recovery.restore_plans SET state='VERIFIED' WHERE id=$1",[p.id]);await cp.prepareCutover(auth("storage.backup.restore"),p,7);const marker=await pool.query("SELECT state,target_id FROM recovery.cutover_markers WHERE owner_id=$1",[owner]);expect(marker.rows[0]).toMatchObject({state:"PREPARED",target_id:p.targetId});});
 it("J0.10-R — Crash and outage recovery reliability",async()=>{const cp=new RecoveryControlPlane(pool,{revalidate:async()=>{}},{verify:async()=>{},activate:async()=>{}},audit,()=>now);await cp.enterSafeMode(owner,null,"RECOVERY_INTERRUPTED");expect(await cp.readiness(owner)).toMatchObject({live:true,ready:false,recoverySafeMode:true});await pool.query("UPDATE recovery.safe_mode SET enabled=false WHERE owner_id=$1",[owner]);expect(await cp.readiness(owner)).toMatchObject({live:true,ready:false,unresolvedCutover:true});await pool.query("UPDATE recovery.cutover_markers SET state='ABORTED' WHERE owner_id=$1",[owner]);expect(await cp.readiness(owner)).toMatchObject({live:true,ready:true});});
});
