import { randomUUID } from "node:crypto";
import { BoundaryError } from "@jarvis/shared";
import { ControlStateSchema, GovernedContextSchema, ToolDescriptorSchema, immutableJson, policyDigest, type ApprovalAuthorityV2, type ControlStatePort, type DeterministicPolicy, type GovernedContext, type ToolDescriptor } from "@jarvis/security";
import type { AuthorizationDecision, ToolAuthorizationPort, ToolDefinitionMetadata, ToolOperation, ToolRequest } from "./j07-contracts.js";

export type GovernedContextResolver=(request:ToolRequest)=>GovernedContext;
const data=(c:ToolRequest["privacyClass"]):ToolDescriptor["data"]=>c==="D5"?"secret":(["D2","D3","D4"].includes(c)?"private":"synthetic");
const descriptor=(tool:ToolDefinitionMetadata,op:ToolOperation,request:ToolRequest):ToolDescriptor=>ToolDescriptorSchema.parse({version:2,id:tool.toolId,scope:op.scope,permission:op.permission,effect:op.sideEffectClass==="READ_ONLY"?"observe":"write",data:data(request.privacyClass),external:tool.boundary==="EXTERNAL_SERVICE",destructive:["DESTRUCTIVE","IRREVERSIBLE","CRITICAL"].includes(op.sideEffectClass),securityChange:tool.category==="SECURITY",financial:tool.category==="FINANCIAL",physical:tool.category==="PHYSICAL"?(op.sideEffectClass==="CRITICAL"?"high":"low"):"none"});
export class J03ToolAuthorizationBridge implements ToolAuthorizationPort {
 constructor(private readonly policy:DeterministicPolicy,private readonly controls:ControlStatePort,private readonly approvals:ApprovalAuthorityV2,private readonly resolveContext:GovernedContextResolver,private readonly clock:()=>number=Date.now){}
 private context(request:ToolRequest){const c=immutableJson(GovernedContextSchema.parse(this.resolveContext(request)));if(c.actor.ownerId!==request.actor.ownerId||c.actor.id!==request.actor.actorId||c.requestId!==request.requestId)throw new BoundaryError("AUTHORIZATION_INVALID");return c;}
 async authorize(request:ToolRequest,op:ToolOperation,inputHash:string,tool:ToolDefinitionMetadata):Promise<AuthorizationDecision>{
  const c=this.context(request),d=descriptor(tool,op,request),state=immutableJson(ControlStateSchema.parse(this.controls.read())),decision=this.policy.evaluate(d,request.resource,c,state,this.clock()),controlHash=policyDigest(state),descriptorHash=policyDigest(d);
  if(!decision.allowed)return{allowed:false,capability:op.capability,resource:request.resource,expiresAt:c.authority.expiresAt,emergencyEpoch:state.epoch,reason:decision.reason,policyHash:decision.policyHash,policyRevision:decision.policyRevision,controlHash,descriptorHash};
  if(decision.requiresApproval){if(!request.approvalReference)return{allowed:false,capability:op.capability,resource:request.resource,expiresAt:c.authority.expiresAt,emergencyEpoch:state.epoch,reason:"approval-required",policyHash:decision.policyHash,policyRevision:decision.policyRevision,controlHash,descriptorHash};const accepted=await this.approvals.consume(request.approvalReference,{version:2,ownerId:c.authority.ownerId,actorId:c.actor.id,deviceId:c.authority.deviceId,sessionId:c.authority.sessionId,environment:c.environment,requestId:c.requestId,toolId:tool.toolId,resource:request.resource,inputHash,descriptorHash,policyHash:decision.policyHash,policyRevision:decision.policyRevision,controlHash,controlEpoch:state.epoch});if(!accepted)return{allowed:false,capability:op.capability,resource:request.resource,expiresAt:c.authority.expiresAt,emergencyEpoch:state.epoch,reason:"approval-denied",policyHash:decision.policyHash,policyRevision:decision.policyRevision,controlHash,descriptorHash};}
  return{allowed:true,authorizationReference:`j07-${randomUUID()}`,approvalReference:request.approvalReference,bindingHash:inputHash,capability:op.capability,resource:request.resource,expiresAt:c.authority.expiresAt,emergencyEpoch:state.epoch,reason:decision.reason,policyHash:decision.policyHash,policyRevision:decision.policyRevision,controlHash,descriptorHash};
 }
 async revalidate(request:ToolRequest,decision:AuthorizationDecision,inputHash:string,op:ToolOperation,tool:ToolDefinitionMetadata):Promise<boolean>{try{const c=this.context(request),d=descriptor(tool,op,request),state=ControlStateSchema.parse(this.controls.read()),fresh=this.policy.evaluate(d,request.resource,c,state,this.clock());return decision.allowed&&decision.bindingHash===inputHash&&decision.expiresAt>this.clock()&&decision.emergencyEpoch===state.epoch&&decision.controlHash===policyDigest(state)&&decision.descriptorHash===policyDigest(d)&&decision.policyHash===fresh.policyHash&&fresh.allowed;}catch{return false;}}
}
