import { readFile,writeFile,appendFile } from "node:fs/promises";
const root=new URL("../",import.meta.url),read=async p=>JSON.parse(await readFile(new URL(p,root),"utf8"));
try{
 const [catalog,unit,integration,j04,j05,j06,j07]=await Promise.all([read("tests/acceptance/j08-gates.json"),read(".jarvis/acceptance/unit.json"),read(".jarvis/acceptance/integration.json"),read(".jarvis/acceptance/j04-go.json"),read(".jarvis/acceptance/j05-go.json"),read(".jarvis/acceptance/j06-go.json"),read(".jarvis/acceptance/j07-go.json")]);
 if(catalog.milestone!=="J0.8 Event System"||catalog.baseline!=="4c05f1d9522d4950e6f9b12a0087290ba74bd5fb"||!Array.isArray(catalog.gates)||catalog.gates.length!==20)throw new Error("GO_CATALOG_INVALID");
 if(j04.result!=="A-S_PASS"||j05.result!=="A-T_PASS"||j06.result!=="A-T_PASS"||j07.result!=="A-T_PASS")throw new Error("PRIOR_REGRESSION_GATE_NOT_PASSING");
 const all=[...unit.testResults.flatMap(s=>s.assertionResults),...integration.testResults.flatMap(s=>s.assertionResults)],letters="ABCDEFGHIJKLMNOPQRST".split("");
 const phases=Object.fromEntries(letters.map((l,i)=>{const title=catalog.gates[i],test=all.find(t=>t.title===title);return[l,{result:test?.status==="passed"?"PASS":"FAIL",assertions:1,failures:test?.status==="passed"?[]:[title],source:test?"all":"missing"}];}));
 const suitesPassed=[unit,integration].every(r=>r.success===true&&r.numFailedTests===0&&r.numPendingTests===0),passed=suitesPassed&&Object.values(phases).every(p=>p.result==="PASS"),result={version:1,milestone:"J0.8",baseline:catalog.baseline,commit:process.env.GITHUB_SHA??null,runId:process.env.GITHUB_RUN_ID??null,typescript:unit.numPassedTests,postgres:integration.numPassedTests,j04Regression:j04.result,j05Regression:j05.result,j06Regression:j06.result,j07Regression:j07.result,phases,result:passed?"A-T_PASS":"A-T_FAIL",verdict:"This verifier never merges or grants GO automatically. Exact-commit CI, browser, outage/recovery, shutdown, Owner merge approval and exact-main validation remain required."};
 await writeFile(new URL(".jarvis/acceptance/j08-go.json",root),JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));if(process.env.GITHUB_STEP_SUMMARY)await appendFile(process.env.GITHUB_STEP_SUMMARY,"\n## J0.8 A–T acceptance\n\nCommit: "+result.commit+"\n\n| Phase | Result |\n|---|---|\n"+Object.entries(phases).map(([l,p])=>`| ${l} | ${p.result} |`).join("\n")+"\n");if(!passed)process.exitCode=1;
}catch(error){console.error("J0.8_A-T_FAIL: missing or invalid acceptance evidence",error instanceof Error?error.message:"unknown");process.exitCode=1;}
