import { describe, expect, it } from "vitest";
import { readFile } from "node:fs/promises";
import { randomUUID } from "node:crypto";
import {
  ContextAssembler, OwnerMemoryControl, PrivateSemanticRetriever, decideMemoryAdmission,
  admissionDecisionHash, rankHybridMemoryCandidates, resolveTruth,
  type PrivateSemanticRecord, type MemoryAuditEvent,
} from "@jarvis/memory";
import { KnowledgeEvidenceEngine, type Entity, type KnowledgeRelationship, type RelationshipEvidence } from "@jarvis/knowledge";
import type { DataPolicy } from "@jarvis/shared";

const policy=(over:Partial<DataPolicy>={}):DataPolicy=>({version:1,classification:"D2",privacy:"ai-allow",retention:{mode:"keep"},consent:{storeConversation:true,createMemory:true,projectKnowledge:true,keepAttachments:true,personalization:true,externalAI:true},...over});
const temporal={capturedAt:"2026-09-03T00:00:00.000Z",observedAt:null,validFrom:"2026-09-03T00:00:00.000Z",validUntil:null,verifiedAt:null,supersededAt:null};
const candidate=(over:Record<string,unknown>={})=>({version:1,candidateId:randomUUID(),ownerId:"owner",projectId:"jarvis",kind:"semantic",subject:"owner",content:"prefers concise summaries",assertion:"OWNER_ASSERTED",confidence:1,policy:policy(),provenance:[{kind:"owner-stated",source:{kind:"conversation",id:"c1",version:1},capturedAt:"2026-09-03T00:00:00.000Z",confidence:1,verifiedAt:null}],derivedFrom:[],temporal,semanticKey:"owner:summary-style",...over});
const record=(over:Partial<PrivateSemanticRecord>={}):PrivateSemanticRecord=>({memoryId:randomUUID(),ownerId:"owner",projectId:"jarvis",content:"prefers concise summaries",policy:policy(),lifecycle:"ACTIVE",assertion:"OWNER_ASSERTED",confidence:1,capturedAt:"2026-09-03T00:00:00.000Z",validUntil:null,semanticVector:[1,0,0],provenanceCount:1,...over});
const kprov={kind:"owner-stated" as const,source:{kind:"person" as const,id:"owner",version:1},capturedAt:"2026-09-03T00:00:00.000Z",confidence:1,verifiedAt:null};
const entity=(name:string):Entity=>({version:1,id:randomUUID(),ownerId:"owner",projectId:"jarvis",type:"project",canonicalName:name,aliases:[],policy:policy({privacy:"private-cloud",consent:{...policy().consent,externalAI:false}}),lifecycle:"ACTIVE",provenance:[kprov],recordVersion:1,createdAt:"2026-09-03T00:00:00.000Z",updatedAt:"2026-09-03T00:00:00.000Z"});
function graphStore(){const entities:Entity[]=[],relationships:KnowledgeRelationship[]=[],evidence:RelationshipEvidence[]=[];return{entities,relationships,evidence,port:{entities:async()=>entities,relationships:async()=>relationships,evidence:async()=>evidence,putEntity:async(e:Entity)=>{entities.push(e)},putRelationship:async(r:KnowledgeRelationship)=>{relationships.push(r)},putEvidence:async(e:RelationshipEvidence)=>{evidence.push(e)}}};}

describe("J0.5 A-T acceptance",()=>{
 it("J0.5 A: protects exact J0.4 baseline and prior milestone regressions",async()=>{const gate=JSON.parse(await readFile("tests/acceptance/j05-gates.json","utf8"));expect(gate.baseline).toBe("ae4ecb03cb9e658a00827dfb3ee8da1d0a88845d");expect(gate.milestone).toBe("J0.5");});
 it("J0.5 B: admits an owner-stated memory with canonical policy and provenance",()=>{const d=decideMemoryAdmission(candidate(),[]);expect(d.decision).toBe("ACCEPT");});
 it("J0.5 C: does not promote an ineligible conversation into durable memory",()=>{const p=policy();p.consent.createMemory=false;expect(decideMemoryAdmission(candidate({policy:p}),[]).decision).toBe("REJECT");});
 it("J0.5 D: preserves model inference as non-owner assertion",()=>{const d=decideMemoryAdmission(candidate({assertion:"MODEL_INFERRED",confidence:.6}),[]);expect(d.decision).toBe("ACCEPT");expect(candidate({assertion:"MODEL_INFERRED"}).assertion).toBe("MODEL_INFERRED");});
 it("J0.5 E: rejects NEVER_STORE and D5 generic memory without derived persistence",()=>{const never=policy({retention:{mode:"never-store"}}),secret=policy({classification:"D5",privacy:"local-only"});expect(decideMemoryAdmission(candidate({policy:never}),[]).decision).toBe("REJECT");expect(decideMemoryAdmission(candidate({policy:secret}),[]).decision).toBe("REJECT");});
 it("J0.5 F: admission replay is idempotent and canonical",()=>{const c=candidate(),d1=decideMemoryAdmission(c,[]),d2=decideMemoryAdmission(c,[]);expect(d1).toEqual(d2);expect(admissionDecisionHash(c as any,d1)).toBe(admissionDecisionHash(c as any,d2));});
 it("J0.5 H: hybrid retrieval favors stronger structured evidence over weak similarity",()=>{const strong=randomUUID(),weak=randomUUID();const ranked=rankHybridMemoryCandidates([{memoryId:strong,lifecycle:"ACTIVE",assertion:"OWNER_ASSERTED",confidence:1,semanticScore:.6,lexicalScore:1,temporalScore:1,projectMatch:true},{memoryId:weak,lifecycle:"ACTIVE",assertion:"MODEL_INFERRED",confidence:.3,semanticScore:.9,lexicalScore:0,temporalScore:.2}],2);expect(ranked[0]?.memoryId).toBe(strong);});
 it("J0.5 I: temporal supersession preserves history and returns current truth",()=>{const old=randomUUID(),fresh=randomUUID();const r=resolveTruth({existing:[{memoryId:old,assertion:"OBSERVED",validFrom:"2026-01-01T00:00:00.000Z",content:"old"}],incoming:{memoryId:fresh,assertion:"OBSERVED",validFrom:"2026-09-01T00:00:00.000Z",content:"new"},ownerConfirmed:false});expect(r).toMatchObject({state:"SUPERSEDE",current:fresh,superseded:[old]});});
 it("J0.5 J: contradictory active propositions produce deterministic conflict state",()=>{const existing={memoryId:randomUUID(),ownerId:"owner",projectId:"jarvis",semanticKey:"x",content:"A",assertion:"IMPORTED",confidence:.8,lifecycle:"ACTIVE",validFrom:null,validUntil:null};expect(decideMemoryAdmission(candidate({semanticKey:"x",content:"B",assertion:"IMPORTED",confidence:.8,temporal:{...temporal,validFrom:null}}),[existing]).decision).toBe("MARK_CONFLICT");});
 it("J0.5 K: owner correction creates authoritative revision without erasing history",async()=>{const history=["old"],id=randomUUID();const store={list:async()=>[record({memoryId:id,content:history.at(-1)!})],correct:async(_o:string,_i:string,c:string)=>{history.push(c)},forget:async()=>{},provenance:async()=>history.map((v,i)=>({revision:i+1,value:v})),conflicts:async()=>[],restrict:async()=>{}};const c=new OwnerMemoryControl(store);await c.correct("owner",id,"new");expect(history).toEqual(["old","new"]);expect((await c.explain("owner",id)).provenance).toHaveLength(2);});
 it("J0.5 L: canonical entity linkage reuses identity and preserves evidence",async()=>{const s=graphStore(),e=new KnowledgeEvidenceEngine(s.port),a=entity("Project JARVIS");await e.upsertCanonicalEntity(a);const r=await e.upsertCanonicalEntity(entity(" project jarvis "));expect(r.deduplicated).toBe(true);expect(r.entity.id).toBe(a.id);});
 it("J0.5 M: relationship evidence links graph facts to surviving source memory",async()=>{const s=graphStore(),e=new KnowledgeEvidenceEngine(s.port),a=entity("A"),b=entity("B"),rid=randomUUID(),mid=randomUUID();s.entities.push(a,b);const rel:KnowledgeRelationship={version:1,id:rid,ownerId:"owner",projectId:"jarvis",sourceEntityId:a.id,predicate:"links",target:{kind:"entity",entityId:b.id},policy:a.policy,status:"ACTIVE",confidence:0,validFrom:null,validUntil:null,evidenceIds:[randomUUID()],recordVersion:1,createdAt:temporal.capturedAt,updatedAt:temporal.capturedAt};const ev:RelationshipEvidence={version:1,id:randomUUID(),ownerId:"owner",relationshipId:rid,sourceMemoryId:mid,sourceRecordId:mid,provenance:kprov,confidence:.9,active:true,createdAt:temporal.capturedAt};const stored=await e.addRelationship(rel,[ev]);expect(stored.evidenceIds).toEqual([ev.id]);expect(await e.invalidateUnsupported("owner",mid)).toEqual([rid]);});
 it("J0.5 N: bounded graph retrieval enforces owner project depth and edge limits",async()=>{const s=graphStore(),e=new KnowledgeEvidenceEngine(s.port),a=entity("A"),b=entity("B"),c=entity("C");s.entities.push(a,b,c);for(const [x,y] of [[a,b],[b,c]] as const){const id=randomUUID(),eid=randomUUID();s.relationships.push({version:1,id,ownerId:"owner",projectId:"jarvis",sourceEntityId:x.id,predicate:"links",target:{kind:"entity",entityId:y.id},policy:a.policy,status:"ACTIVE",confidence:1,validFrom:null,validUntil:null,evidenceIds:[eid],recordVersion:1,createdAt:temporal.capturedAt,updatedAt:temporal.capturedAt});s.evidence.push({version:1,id:eid,ownerId:"owner",relationshipId:id,sourceMemoryId:randomUUID(),sourceRecordId:randomUUID(),provenance:kprov,confidence:1,active:true,createdAt:temporal.capturedAt});}const r=await e.traverse({version:1,ownerId:"owner",projectId:"jarvis",startEntityIds:[a.id],predicates:[],asOf:"2026-09-03T12:00:00.000Z",maxDepth:1,maxEdges:1,includeDisputed:false});expect(r.relationships).toHaveLength(1);expect(r.truncated).toBe(true);});
 it("J0.5 O: context minimization selects only budgeted highest-value evidence",async()=>{const a=record({content:"A"}),b=record({content:"B"});const retrieval=await new PrivateSemanticRetriever().retrieve({ownerId:"owner",projectId:"jarvis",query:"A",queryVector:[1,0,0],asOf:"2026-09-03T12:00:00.000Z",limit:10,records:[a,b]});const p=await new ContextAssembler().assemble({version:1,ownerId:"owner",projectId:"jarvis",purpose:"answer",query:"A",processingTarget:"APPROVED_EXTERNAL_AI",providerId:"synthetic",budget:{maxMemories:1,maxGraphFacts:0,maxCharacters:100,maxRelationshipDepth:0,maxAgeDays:null}},[a,b],retrieval,[]);expect(p.items).toHaveLength(1);expect(p.exclusions.some(x=>x.reason==="BUDGET")).toBe(true);});
 it("J0.5 P: external context excludes D5 and NEVER_EXTERNAL before provider boundary",async()=>{const ok=record(),secret=record({policy:policy({classification:"D5",privacy:"local-only"})}),local=record({policy:policy({privacy:"private-cloud",consent:{...policy().consent,externalAI:false}})});const candidates=[ok,secret,local].map(m=>({memoryId:m.memoryId,score:1,reasons:["SEMANTIC_SIMILARITY" as const],lifecycle:"ACTIVE" as const,assertion:m.assertion,confidence:m.confidence}));const retrieval={version:1 as const,query:{version:1 as const,ownerId:"owner",projectId:"jarvis",query:"x",kinds:[],entityIds:[],includeDisputed:false,asOf:"2026-09-03T12:00:00.000Z",limit:10},candidates,degraded:false,degradationReasons:[]};const p=await new ContextAssembler().assemble({version:1,ownerId:"owner",projectId:"jarvis",purpose:"answer",query:"x",processingTarget:"APPROVED_EXTERNAL_AI",providerId:"synthetic",budget:{maxMemories:10,maxGraphFacts:0,maxCharacters:1000,maxRelationshipDepth:0,maxAgeDays:null}},[ok,secret,local],retrieval,[]);expect(p.items.map(x=>x.memoryId)).toEqual([ok.memoryId]);expect(p.exclusions.map(x=>x.reason)).toEqual(expect.arrayContaining(["D5_SECRET","NEVER_EXTERNAL"]));});
 it("J0.5 S: retrieval failure closes safely or explicitly reports permitted degradation",async()=>{const r=await new PrivateSemanticRetriever().retrieve({ownerId:"owner",projectId:"jarvis",query:"x",queryVector:[1,0],asOf:"2026-09-03T12:00:00.000Z",limit:10,records:[record()]});expect(r.degraded).toBe(true);expect(r.candidates).toEqual([]);});
 it("J0.5 T: owner inspection exposes evidence conflicts and context preview with safe audit",async()=>{const events:MemoryAuditEvent[]=[],id=randomUUID(),store={list:async()=>[record({memoryId:id})],correct:async()=>{},forget:async()=>{},provenance:async()=>[{source:"owner"}],conflicts:async()=>[{id:"conflict"}],restrict:async()=>{}};const audit={append:(e:MemoryAuditEvent)=>{events.push(e)}};const control=new OwnerMemoryControl(store,audit);expect(await control.inspect("owner")).toHaveLength(1);expect((await control.explain("owner",id)).provenance).toHaveLength(1);expect(await control.showConflicts("owner")).toHaveLength(1);await control.correct("owner",id,"corrected");expect(events[0]?.action).toBe("correct");});
});
