import { describe, expect, it } from "vitest";
import { randomUUID } from "node:crypto";
import { KnowledgeEvidenceEngine, type Entity, type KnowledgeRelationship, type RelationshipEvidence } from "@jarvis/knowledge";
import type { DataPolicy } from "@jarvis/shared";
const policy:DataPolicy={version:1,classification:"D2",privacy:"private-cloud",retention:{mode:"keep"},consent:{storeConversation:true,createMemory:true,projectKnowledge:true,keepAttachments:true,personalization:true,externalAI:false}};
const prov={kind:"owner-stated" as const,source:{kind:"person" as const,id:"owner",version:1},capturedAt:"2026-09-03T00:00:00.000Z",confidence:1,verifiedAt:"2026-09-03T00:00:00.000Z"};
const entity=(name:string):Entity=>({version:1,id:randomUUID(),ownerId:"owner",projectId:"jarvis",type:"project",canonicalName:name,aliases:[],policy,lifecycle:"ACTIVE",provenance:[prov],recordVersion:1,createdAt:"2026-09-03T00:00:00.000Z",updatedAt:"2026-09-03T00:00:00.000Z"});
function memoryStore(){const entities:Entity[]=[],relationships:KnowledgeRelationship[]=[],evidence:RelationshipEvidence[]=[];return {entities,relationships,evidence,store:{entities:async()=>entities,relationships:async()=>relationships,evidence:async()=>evidence,putEntity:async(e:Entity)=>{entities.push(e)},putRelationship:async(r:KnowledgeRelationship)=>{relationships.push(r)},putEvidence:async(e:RelationshipEvidence)=>{evidence.push(e)}}};}
describe("J0.5 knowledge evidence engine",()=>{
 it("deduplicates canonical entities using normalized name and aliases",async()=>{const m=memoryStore(), engine=new KnowledgeEvidenceEngine(m.store), a=entity("Project JARVIS"); await engine.upsertCanonicalEntity(a); const b=entity("  project   jarvis "); const r=await engine.upsertCanonicalEntity(b); expect(r.deduplicated).toBe(true); expect(m.entities).toHaveLength(1);});
 it("requires evidence and derives confidence from active evidence",async()=>{const m=memoryStore(), engine=new KnowledgeEvidenceEngine(m.store), a=entity("A"), b=entity("B"); m.entities.push(a,b); const id=randomUUID(); const r:KnowledgeRelationship={version:1,id,ownerId:"owner",projectId:"jarvis",sourceEntityId:a.id,predicate:"depends_on",target:{kind:"entity",entityId:b.id},policy,status:"ACTIVE",confidence:0,validFrom:null,validUntil:null,evidenceIds:[randomUUID()],recordVersion:1,createdAt:"2026-09-03T00:00:00.000Z",updatedAt:"2026-09-03T00:00:00.000Z"}; await expect(engine.addRelationship(r,[])).rejects.toThrow("KNOWLEDGE_EVIDENCE_REQUIRED"); const e:RelationshipEvidence={version:1,id:randomUUID(),ownerId:"owner",relationshipId:id,sourceMemoryId:randomUUID(),sourceRecordId:randomUUID(),provenance:prov,confidence:.8,active:true,createdAt:"2026-09-03T00:00:00.000Z"}; const stored=await engine.addRelationship(r,[e]); expect(stored.confidence).toBe(.8); expect(await engine.recomputeConfidence("owner",id)).toBe(.8);});
 it("enforces temporal/project/depth/edge bounds during traversal",async()=>{const m=memoryStore(), engine=new KnowledgeEvidenceEngine(m.store), a=entity("A"),b=entity("B"),c=entity("C"); m.entities.push(a,b,c); const mk=(s:string,t:string):KnowledgeRelationship=>({version:1,id:randomUUID(),ownerId:"owner",projectId:"jarvis",sourceEntityId:s,predicate:"links",target:{kind:"entity",entityId:t},policy,status:"ACTIVE",confidence:1,validFrom:"2026-01-01T00:00:00.000Z",validUntil:null,evidenceIds:[randomUUID()],recordVersion:1,createdAt:"2026-01-01T00:00:00.000Z",updatedAt:"2026-01-01T00:00:00.000Z"}); m.relationships.push(mk(a.id,b.id),mk(b.id,c.id)); for(const r of m.relationships)m.evidence.push({version:1,id:r.evidenceIds[0]!,ownerId:"owner",relationshipId:r.id,sourceMemoryId:randomUUID(),sourceRecordId:randomUUID(),provenance:prov,confidence:1,active:true,createdAt:"2026-01-01T00:00:00.000Z"}); const result=await engine.traverse({version:1,ownerId:"owner",projectId:"jarvis",startEntityIds:[a.id],predicates:[],asOf:"2026-09-03T00:00:00.000Z",maxDepth:1,maxEdges:1,includeDisputed:false}); expect(result.relationships).toHaveLength(1); expect(result.truncated).toBe(true);});
 it("identifies graph facts whose evidence disappears with forgotten memory",async()=>{const m=memoryStore(),engine=new KnowledgeEvidenceEngine(m.store),memoryId=randomUUID(),rel=randomUUID();m.evidence.push({version:1,id:randomUUID(),ownerId:"owner",relationshipId:rel,sourceMemoryId:memoryId,sourceRecordId:randomUUID(),provenance:prov,confidence:1,active:true,createdAt:"2026-01-01T00:00:00.000Z"});expect(await engine.invalidateUnsupported("owner",memoryId)).toEqual([rel]);});
});
