import { describe,expect,it,vi } from "vitest";
import { J03ToolAuthorizationBridge,J04CredentialBroker,MemoryToolExecutionStore,ResourceLockManager,ToolLifecycle,UniversalToolGateway,UniversalToolRegistry,syntheticTool,type CredentialBroker,type ToolAuditEvent,type ToolRequest } from "@jarvis/tools";
import { DeterministicPolicy,type ApprovalBindingV2,type SecretManager } from "@jarvis/security";
import { policyContext,policyControls,policyDocument,policyNow } from "../fixtures/policy.js";
const req=(over:Partial<ToolRequest>={}):ToolRequest=>({requestId:"request-test",correlationId:"cor-1",actor:{ownerId:"owner-test",actorId:"agent-test",role:"AGENT"},projectId:"jarvis",source:"AGENT",toolId:"mock.repository.read",toolVersion:1,operation:"run",input:{key:"k",value:"v"},resource:"repository-x",privacyClass:"D0",requestedMode:"EXECUTE",deadlineEpochMs:policyNow+5000,maxCostMinor:10,metadata:{},...over});
const emptyBroker:CredentialBroker={lease:async()=>undefined};
function realSecurity(tool=syntheticTool("mock.repository.read","read",{operations:[{operation:"run",capability:"mock.read",scope:"mock.read",permission:"P0",sideEffectClass:"READ_ONLY",supportsDryRun:true,supportsIdempotency:true,supportsCancellation:false,supportsVerification:true,rollback:"NONE",maxAttempts:2,timeoutMs:1000,retryBaseMs:1,estimatedCostMinor:1}]})){const controls=policyControls(),policy=new DeterministicPolicy(policyDocument()),consume=vi.fn(async(_p:string,_b:ApprovalBindingV2)=>true),bridge=new J03ToolAuthorizationBridge(policy,{read:()=>controls},{consume},r=>({...policyContext(),requestId:r.requestId}),()=>policyNow),events:ToolAuditEvent[]=[];return{controls,consume,bridge,gateway:new UniversalToolGateway(new UniversalToolRegistry([tool]),bridge,emptyBroker,{append:async e=>{events.push(e);}},new MemoryToolExecutionStore(),()=>policyNow),events};}
describe("J0.7 hardening",()=>{
 it("uses the actual J0.3 deterministic policy and rechecks control state",async()=>{const x=realSecurity();expect((await x.gateway.invoke(req())).status).toBe("VERIFIED");x.controls.frozen=true;x.controls.epoch++;await expect(x.gateway.invoke(req({requestId:"request-two"}))).rejects.toThrow("AUTHORIZATION_INVALID");});
 it("rejects cross-owner context before adapter dispatch",async()=>{const x=realSecurity();await expect(x.gateway.invoke(req({actor:{ownerId:"other",actorId:"agent-test",role:"AGENT"}}))).rejects.toThrow("AUTHORIZATION_INVALID");});
 it("adapts J0.4 SecretManager leases without exposing the vault reference",async()=>{const destroyed=vi.fn(),manager:SecretManager={lease:vi.fn(async()=>({value:Buffer.from("hidden-secret"),expiresAt:Date.now()+1000,destroy:destroyed}))},broker=new J04CredentialBroker(manager,()=>policyContext().actor,new Map([["synthetic.secret","development/tools/synthetic-credential"]]));const lease=await broker.lease(["synthetic.secret"],req());expect(lease?.handle).not.toContain("development/tools");expect(await lease?.use(async s=>s.length)).toBe(13);expect(destroyed).toHaveBeenCalledOnce();});
 it("rejects credential plaintext returned by a malicious adapter",async()=>{const tool=syntheticTool("mock.repository.read","secret-leak",{operations:[{operation:"run",capability:"mock.read",scope:"mock.read",permission:"P0",sideEffectClass:"READ_ONLY",supportsDryRun:true,supportsIdempotency:true,supportsCancellation:false,supportsVerification:true,rollback:"NONE",maxAttempts:1,timeoutMs:1000,retryBaseMs:0,estimatedCostMinor:1}]});const x=realSecurity(tool),broker:CredentialBroker={lease:async()=>({handle:"opaque",expiresAt:Date.now()+1000,use:async fn=>fn("never-leak-me")})},gateway=new UniversalToolGateway(new UniversalToolRegistry([tool]),x.bridge,broker,{append:async()=>{}},undefined,()=>policyNow);await expect(gateway.invoke(req())).rejects.toThrow("INVALID_OUTPUT");});
 it("enforces estimated and actual cost budgets before reporting success",async()=>{const x=realSecurity();await expect(x.gateway.invoke(req({maxCostMinor:0}))).rejects.toThrow("COST_BUDGET_EXCEEDED");});
 it("supports verification-only and policy-controlled rollback against stored executions",async()=>{const write=syntheticTool("mock.repository.read","write",{operations:[{operation:"run",capability:"mock.read",scope:"mock.read",permission:"P3",sideEffectClass:"REVERSIBLE_WRITE",supportsDryRun:true,supportsIdempotency:true,supportsCancellation:false,supportsVerification:true,rollback:"COMPENSATING_ACTION",maxAttempts:1,timeoutMs:1000,retryBaseMs:0,estimatedCostMinor:1}]}),x=realSecurity(write);x.controls.mode="autonomous";const done=await x.gateway.invoke(req({idempotencyKey:"write-1"})),verified=await x.gateway.invoke(req({requestId:"verify-1",requestedMode:"VERIFY_ONLY",executionReference:done.executionId}));expect(verified.status).toBe("VERIFIED");const rolled=await x.gateway.invoke(req({requestId:"rollback-1",requestedMode:"ROLLBACK",executionReference:done.executionId}));expect(rolled.status).toBe("ROLLED_BACK");});
 it("rejects illegal lifecycle transitions and conflicting resource mutation locks",()=>{const life=new ToolLifecycle();expect(()=>life.transition("VERIFIED")).toThrow("ILLEGAL_TOOL_STATE_TRANSITION");const locks=new ResourceLockManager(),release=locks.acquire("resource");expect(()=>locks.acquire("resource")).toThrow("CONCURRENCY_CONFLICT");release();expect(()=>locks.acquire("resource")).not.toThrow();});
 it("allows owner health controls to disable registered tools",()=>{const registry=new UniversalToolRegistry([syntheticTool("mock.read","read")]);registry.setHealth("mock.read",1,"DISABLED");expect(()=>registry.get("mock.read",1)).toThrow("TOOL_DISABLED");});
});
