import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";
import { UniversalToolGateway, UniversalToolRegistry, SyntheticToolAdapter, syntheticTool, toolInputDigest, type AuthorizationDecision, type CredentialBroker, type ToolAuditEvent, type ToolAuthorizationPort, type ToolRequest } from "@jarvis/tools";

const baseline="3eb07b904ac1e2f9be20a9e52008df824816b774";
const request=(over:Partial<ToolRequest>={}):ToolRequest=>({requestId:"req-1",correlationId:"cor-1",actor:{ownerId:"owner",actorId:"owner",role:"OWNER"},projectId:"jarvis",source:"USER",toolId:"mock.read",toolVersion:1,operation:"run",input:{key:"k",value:"v"},resource:"jarvis",privacyClass:"D1",requestedMode:"EXECUTE",deadlineEpochMs:Date.now()+5000,metadata:{},...over});
class Auth implements ToolAuthorizationPort { allowed=true; epoch=1; delegated=true; rotateAfterAuthorize=false; async authorize(r:ToolRequest,o:{capability:string},hash:string):Promise<AuthorizationDecision>{const decision={allowed:this.allowed&&this.delegated,authorizationReference:"auth-1",bindingHash:hash,capability:o.capability,resource:r.resource,expiresAt:Date.now()+10000,emergencyEpoch:this.epoch,reason:"policy"};if(this.rotateAfterAuthorize)this.epoch+=1;return decision;} async revalidate(_r:ToolRequest,d:AuthorizationDecision,hash:string){return this.allowed&&this.delegated&&d.bindingHash===hash&&d.emergencyEpoch===this.epoch;} }
class Broker implements CredentialBroker { leases=0; async lease(){this.leases+=1;return{handle:"vault:opaque",expiresAt:Date.now()+1000,use:async<T>(fn:(s:string)=>Promise<T>)=>fn("super-secret")};} }
const build=(tools=[syntheticTool("mock.read","read")])=>{const auth=new Auth(),broker=new Broker(),events:ToolAuditEvent[]=[];const gateway=new UniversalToolGateway(new UniversalToolRegistry(tools),auth,broker,{append:async e=>{events.push(e);}});return{auth,broker,events,gateway};};

describe("J0.7 A-T",()=>{
 it("A preserves the exact J0.6 baseline and prior regressions",()=>{expect(readFileSync("tests/acceptance/j07-gates.json","utf8")).toContain(baseline);});
 it("B invokes a tool through provider-neutral J0.7 contracts",async()=>{const{gateway}=build();const r=await gateway.invoke(request());expect(r.toolId).toBe("mock.read");expect(r.verified).toBe(true);});
 it("C requires explicit registered tool identity and version",async()=>{const{gateway}=build();await expect(gateway.invoke(request({toolId:"fake"}))).rejects.toThrow("TOOL_NOT_FOUND");await expect(gateway.invoke(request({toolVersion:2}))).rejects.toThrow("TOOL_NOT_FOUND");});
 it("D rejects invalid input and malformed output",async()=>{let x=build();await expect(x.gateway.invoke(request({input:{bad:true}}))).rejects.toThrow("INVALID_INPUT");x=build([syntheticTool("mock.read","malformed")]);await expect(x.gateway.invoke(request())).rejects.toThrow("INVALID_OUTPUT");});
 it("E denies execution before adapter dispatch when J0.3 authorization rejects",async()=>{const adapter=new SyntheticToolAdapter("read"),x=build([syntheticTool("mock.read","read",{},adapter)]);x.auth.allowed=false;await expect(x.gateway.invoke(request())).rejects.toThrow("AUTHORIZATION_INVALID");expect(adapter.calls).toBe(0);});
 it("F binds authorization to exact normalized input and rejects alteration",async()=>{const x=build();const good=toolInputDigest({toolId:"mock.read",toolVersion:1,operation:"run",resource:"jarvis",input:{key:"k",value:"v"}});await expect(x.gateway.invoke(request({inputHash:good,input:{key:"k",value:"changed"}}))).rejects.toThrow("AUTHORIZATION_INVALID");});
 it("G keeps model proposals isolated from adapters and credentials",async()=>{const x=build();const r=await x.gateway.invoke(request({source:"MODEL"}));expect(r.output).not.toHaveProperty("handle");expect(x.broker.leases).toBe(0);});
 it("H enforces delegated actor scope through the authorization boundary",async()=>{const x=build();x.auth.delegated=false;await expect(x.gateway.invoke(request({actor:{ownerId:"owner",actorId:"agent",role:"AGENT"},source:"AGENT"}))).rejects.toThrow("AUTHORIZATION_INVALID");});
 it("I denies forbidden external data egress including D5/local-only data",async()=>{const tool=syntheticTool("mock.read","read",{boundary:"EXTERNAL_SERVICE",allowedClassifications:["D0","D1","D2","D3","D4","D5"]});const x=build([tool]);await expect(x.gateway.invoke(request({privacyClass:"D5",metadata:{externalAllowed:"true"}}))).rejects.toThrow("PRIVACY_DENIED");await expect(x.gateway.invoke(request({metadata:{}}))).rejects.toThrow("PRIVACY_DENIED");});
 it("J brokers credentials only at dispatch and redacts them from results and audit",async()=>{const x=build([syntheticTool("mock.secret","secret")]);const r=await x.gateway.invoke(request({toolId:"mock.secret",idempotencyKey:"idem-secret"}));expect(x.broker.leases).toBe(1);expect(JSON.stringify(r)).not.toContain("super-secret");expect(JSON.stringify(x.events)).not.toContain("super-secret");});
 it("K simulates or dry-runs without mutation or implicit execution authority",async()=>{const adapter=new SyntheticToolAdapter("write"),x=build([syntheticTool("mock.write","write",{},adapter)]);const r=await x.gateway.invoke(request({toolId:"mock.write",requestedMode:"SIMULATE"}));expect(r.status).toBe("SIMULATED");expect(adapter.effects).toBe(0);});
 it("L prevents duplicate effects and rejects idempotency key conflicts",async()=>{const adapter=new SyntheticToolAdapter("write"),x=build([syntheticTool("mock.write","write",{},adapter)]),a=request({toolId:"mock.write",idempotencyKey:"same"});const one=await x.gateway.invoke(a),two=await x.gateway.invoke({...a,requestId:"req-2"});expect(two.executionId).toBe(one.executionId);expect(adapter.effects).toBe(1);await expect(x.gateway.invoke(request({toolId:"mock.write",idempotencyKey:"same",input:{key:"k",value:"other"}}))).rejects.toThrow("IDEMPOTENCY_CONFLICT");});
 it("M enforces deadlines and truthful cancellation semantics",async()=>{const x=build([syntheticTool("mock.slow","slow")]);await expect(x.gateway.invoke(request({toolId:"mock.slow",deadlineEpochMs:Date.now()+5,idempotencyKey:"slow"}))).rejects.toThrow("UNKNOWN_OUTCOME");});
 it("N bounds retries and never blindly retries unsafe mutation",async()=>{const readAdapter=new SyntheticToolAdapter("failure"),x=build([syntheticTool("mock.read","failure",{},readAdapter)]);await expect(x.gateway.invoke(request())).rejects.toThrow("RETRY_EXHAUSTED");expect(readAdapter.calls).toBe(2);const mut=new SyntheticToolAdapter("failure"),y=build([syntheticTool("mock.irreversible","irreversible",{},mut)]);await expect(y.gateway.invoke(request({toolId:"mock.irreversible",idempotencyKey:"irr"}))).rejects.toThrow();expect(mut.calls).toBe(1);});
 it("O treats timeout after possible mutation as UNKNOWN_OUTCOME and reconciles",async()=>{const adapter=new SyntheticToolAdapter("ambiguous"),x=build([syntheticTool("mock.ambiguous","ambiguous",{},adapter)]);const r=await x.gateway.invoke(request({toolId:"mock.ambiguous",idempotencyKey:"amb"}));expect(r.status).toBe("RECONCILED");expect(adapter.effects).toBe(1);expect(adapter.calls).toBe(1);});
 it("P separates provider success from independent verification",async()=>{const adapter=new SyntheticToolAdapter("read",25,false),x=build([syntheticTool("mock.read","read",{},adapter)]);await expect(x.gateway.invoke(request())).rejects.toThrow("VERIFICATION_FAILED");});
 it("Q revalidates emergency and authorization state immediately before dispatch",async()=>{const x=build();x.auth.rotateAfterAuthorize=true;await expect(x.gateway.invoke(request())).rejects.toThrow("EMERGENCY_STOP");});
 it("R treats tool output and prompt injection as untrusted data without authority",async()=>{const x=build([syntheticTool("mock.read","injection")]);const r=await x.gateway.invoke(request());expect(r.provenance).toBe("UNTRUSTED_EXTERNAL_DATA");expect(JSON.stringify(r.output)).toContain("Ignore policy");expect(r.verified).toBe(true);});
 it("S emits safe deterministic audit and provenance without secret leakage",async()=>{const x=build();await x.gateway.invoke(request());expect(x.events.some(e=>e.event==="TOOL_DISPATCHED")).toBe(true);expect(x.events.some(e=>e.event==="TOOL_VERIFIED")).toBe(true);expect(JSON.stringify(x.events)).not.toContain('"input"');});
 it("T runs the complete universal gateway path with verification, reconciliation and provider-independent authority",async()=>{const write=new SyntheticToolAdapter("write"),amb=new SyntheticToolAdapter("ambiguous"),x=build([syntheticTool("mock.write","write",{},write),syntheticTool("mock.ambiguous","ambiguous",{},amb)]);const sim=await x.gateway.invoke(request({toolId:"mock.write",requestedMode:"SIMULATE"}));expect(sim.status).toBe("SIMULATED");const done=await x.gateway.invoke(request({toolId:"mock.write",idempotencyKey:"full"}));expect(done.status).toBe("VERIFIED");const reconciled=await x.gateway.invoke(request({toolId:"mock.ambiguous",idempotencyKey:"full-amb"}));expect(reconciled.status).toBe("RECONCILED");expect(x.events.every(e=>!JSON.stringify(e).includes("super-secret"))).toBe(true);});
});
