import { createHmac, randomUUID } from "node:crypto";
import { describe,expect,it,vi } from "vitest";
import { J03EventConsumerAuthorization } from "@jarvis/core";
import { EventAdmissionLimiter,EventControlPlane,EventRouter,EventSystem,EventSystemError,EventTypeRegistry,ExternalEventIngress,GracefulEventWorkerGate,HmacIngressAuthenticator,MemoryEventStore,MemoryIngressReceipts,jsonPayload,type EventAdminStorePort,type EventEvidence,type EventSubscription,type JarvisEventEnvelope } from "@jarvis/events";

const now="2026-09-03T15:00:00.000Z",owner="owner-hardening";
const event=(over:Partial<JarvisEventEnvelope>={}):JarvisEventEnvelope=>({eventId:randomUUID(),eventType:"system.hardening",schemaVersion:1,occurredAt:now,receivedAt:now,ownerId:owner,projectId:"jarvis",correlationId:"hardening",producerId:"jarvis.system",producerType:"SYSTEM",subject:"hardening",payload:{reference:"safe"},payloadClassification:"D1",privacy:"private-cloud",chainDepth:0,...over});
class Evidence{events:EventEvidence[]=[];async append(e:EventEvidence){this.events.push(e);}}
const setup=()=>{const store=new MemoryEventStore(),evidence=new Evidence(),registry=new EventTypeRegistry();registry.register({eventType:"system.hardening",schemaVersion:1,payloadSchema:jsonPayload,allowedProducerTypes:["SYSTEM","EXTERNAL"],maxClassification:"D4",replayPolicy:"OWNER_ONLY",maxPayloadBytes:256});const router=new EventRouter(store,{authorize:async()=>true},evidence),system=new EventSystem(registry,store,router,evidence);return{store,evidence,registry,router,system};};

describe("J0.8 adversarial hardening",()=>{
 it("rejects wildcard privileged subscriptions",()=>{const x=setup();expect(()=>x.router.subscribe({subscriptionId:"wild",consumerId:"c",consumerType:"SERVICE",eventType:"system.*",ownerId:owner,boundary:"LOCAL",maxClassification:"D4",enabled:true,maxAttempts:1,baseBackoffMs:0,ordered:false,deadLetter:true} as EventSubscription)).toThrow();});
 it("bounds event storms per owner and producer",()=>{let clock=0;const limiter=new EventAdmissionLimiter(2,2,1000,()=>clock),a=event();limiter.check(a);limiter.check({...a,eventId:randomUUID()});expect(()=>limiter.check({...a,eventId:randomUUID()})).toThrow("EVENT_BACKPRESSURE");clock=1001;expect(()=>limiter.check({...a,eventId:randomUUID()})).not.toThrow();});
 it("rejects invalid external signatures before durable event acceptance",async()=>{const x=setup(),receipts=new MemoryIngressReceipts(),ingress=new ExternalEventIngress(x.system,new Map([["provider",{producerId:"provider",ownerId:owner,projectId:"jarvis",eventType:"system.hardening",schemaVersion:1,subject:"external",classification:"D1",privacy:"private-cloud"}]]),new HmacIngressAuthenticator(async()=>"key",300_000,()=>Date.parse(now)),receipts,x.evidence);await expect(ingress.ingest({producerId:"provider",sourceEventId:"source",timestamp:Date.parse(now),signature:"00",rawBody:'{"ok":true}'})).rejects.toThrow("INGRESS_AUTH_INVALID");expect(x.store.events.size).toBe(0);});
 it("rejects oversized ingress before authenticating",async()=>{const x=setup(),verify=vi.fn(async()=>true),ingress=new ExternalEventIngress(x.system,new Map([["provider",{producerId:"provider",ownerId:owner,eventType:"system.hardening",schemaVersion:1,subject:"external",classification:"D1",privacy:"private-cloud"}]]),{verify},new MemoryIngressReceipts(),x.evidence,8);await expect(ingress.ingest({producerId:"provider",sourceEventId:"source",timestamp:Date.parse(now),signature:"00",rawBody:'{"oversized":true}'})).rejects.toThrow("PAYLOAD_TOO_LARGE");expect(verify).not.toHaveBeenCalled();});
 it("uses trusted producer owner mapping instead of payload owner claims",async()=>{const x=setup(),key="key",timestamp=Date.parse(now),rawBody=JSON.stringify({ownerId:"attacker",reference:"safe"}),source="trusted-source",signature=createHmac("sha256",key).update(`${timestamp}.${source}..${rawBody}`).digest("hex"),ingress=new ExternalEventIngress(x.system,new Map([["provider",{producerId:"provider",ownerId:owner,projectId:"jarvis",eventType:"system.hardening",schemaVersion:1,subject:"external",classification:"D1",privacy:"private-cloud"}]]),new HmacIngressAuthenticator(async()=>key,300_000,()=>timestamp),new MemoryIngressReceipts(),x.evidence);const result=await ingress.ingest({producerId:"provider",sourceEventId:source,timestamp,signature,rawBody});expect(result.event.ownerId).toBe(owner);expect(result.event.payload.ownerId).toBe("attacker");});
 it("reuses J0.3 emergency state before consumer policy authorization",async()=>{const state={version:1 as const,epoch:1,flags:["AGENTS_FROZEN" as const],frozenActors:[] as string[]},policy=vi.fn(async()=>true),auth=new J03EventConsumerAuthorization({read:()=>state},policy),agent={subscriptionId:"agent-sub",consumerId:"agent-1",consumerType:"AGENT" as const,eventType:"system.hardening",ownerId:owner,boundary:"LOCAL" as const,maxClassification:"D4" as const,enabled:true,maxAttempts:1,baseBackoffMs:0,ordered:false,deadLetter:true};expect(await auth.authorize(agent,event())).toBe(false);expect(policy).not.toHaveBeenCalled();state.flags=[];expect(await auth.authorize(agent,event())).toBe(true);expect(policy).toHaveBeenCalledOnce();});
 it("keeps completed deliveries completed when cancellation is requested",async()=>{const x=setup(),e=event();await x.store.accept(e);await x.store.claimInbox(e.eventId,"consumer");await x.store.completeInbox(e.eventId,"consumer");const admin:EventAdminStorePort={load:id=>x.store.load(id),cancelDelivery:async(id,c)=>x.store.inbox.get(`${id}:${c}`)==="completed"?"completed":"missing",cancelSchedule:async()=>false,listDeadLetters:async()=>[]},control=new EventControlPlane(x.system,x.registry,x.router,admin);expect(await control.cancelDelivery(owner,e.eventId,"consumer")).toBe("completed");});
 it("enforces owner scope for event control-plane replay",async()=>{const x=setup(),e=event();await x.system.accept(e);const admin:EventAdminStorePort={load:id=>x.store.load(id),cancelDelivery:async()=>"missing",cancelSchedule:async()=>false,listDeadLetters:async()=>[]},control=new EventControlPlane(x.system,x.registry,x.router,admin);await expect(control.replay("other-owner",e.eventId,"attack")).rejects.toThrow("OWNER_SCOPE_DENIED");});
 it("stops accepting new work and drains in-flight work on shutdown",async()=>{const gate=new GracefulEventWorkerGate(),leave=gate.enter();gate.beginShutdown();expect(()=>gate.enter()).toThrow("EVENT_WORKER_DRAINING");leave();await expect(gate.drain(50)).resolves.toBeUndefined();expect(gate.status()).toEqual({accepting:false,inFlight:0});});
 it("redacts nested secret-like evidence fields",async()=>{const {safeEventMetadata}=await import("@jarvis/events");expect(safeEventMetadata({ok:"yes",nested:{accessToken:"hidden",value:"safe"},credentials:{password:"hidden"}})).toEqual({ok:"yes",nested:{value:"safe"}});});
 it("rejects unsupported schema versions and oversized normalized payloads",async()=>{const x=setup();await expect(x.system.accept(event({schemaVersion:2}))).rejects.toThrow("EVENT_TYPE_UNKNOWN");await expect(x.system.accept(event({payload:{text:"x".repeat(500)}}))).rejects.toThrow("PAYLOAD_TOO_LARGE");});
});
