import { createHmac, randomUUID } from "node:crypto";
import { readFileSync } from "node:fs";
import { describe,expect,it,vi } from "vitest";
import { EventRouter,EventScheduler,EventSystem,EventSystemError,EventTypeRegistry,ExternalEventIngress,HmacIngressAuthenticator,MemoryEventStore,MemoryIngressReceipts,jsonPayload,safeEventMetadata,type ConsumerAuthorizationPort,type EventEvidence,type EventSchedule,type EventSubscription,type EventTypeDefinition,type JarvisEventEnvelope } from "@jarvis/events";
import { GovernedEventToolConsumer } from "@jarvis/core";
import { SyntheticToolAdapter,UniversalToolGateway,UniversalToolRegistry,syntheticTool,type AuthorizationDecision,type CredentialBroker,type ToolAuthorizationPort,type ToolRequest } from "@jarvis/tools";

const now="2026-09-03T15:00:00.000Z",owner="owner-j08",project="jarvis";
const definition=(eventType="system.test"):EventTypeDefinition=>({eventType,schemaVersion:1,payloadSchema:jsonPayload,allowedProducerTypes:["INTERNAL","EXTERNAL","SCHEDULED","SYSTEM"],maxClassification:"D4",replayPolicy:"OWNER_ONLY",maxPayloadBytes:8192});
const event=(over:Partial<JarvisEventEnvelope>={}):JarvisEventEnvelope=>({eventId:randomUUID(),eventType:"system.test",schemaVersion:1,occurredAt:now,receivedAt:now,ownerId:owner,projectId:project,correlationId:"corr-j08",producerId:"jarvis.system",producerType:"SYSTEM",subject:"test",payload:{value:"ok"},payloadClassification:"D1",privacy:"private-cloud",chainDepth:0,...over});
class Evidence{events:EventEvidence[]=[];async append(e:EventEvidence){this.events.push(e);}}
class ConsumerAuth implements ConsumerAuthorizationPort{allow=true;async authorize(s:EventSubscription,e:JarvisEventEnvelope){return this.allow&&s.ownerId===e.ownerId&&(s.projectId===undefined||s.projectId===e.projectId);}}
const sub=(over:Partial<EventSubscription>={}):EventSubscription=>({subscriptionId:"sub-1",consumerId:"consumer-1",consumerType:"SERVICE",eventType:"system.test",ownerId:owner,projectId:project,boundary:"LOCAL",maxClassification:"D4",enabled:true,maxAttempts:3,baseBackoffMs:1,ordered:false,deadLetter:true,...over});
function system(eventType="system.test"){const store=new MemoryEventStore(),evidence=new Evidence(),auth=new ConsumerAuth(),router=new EventRouter(store,auth,evidence),registry=new EventTypeRegistry();registry.register(definition(eventType));const sys=new EventSystem(registry,store,router,evidence);return{store,evidence,auth,router,registry,sys};}
class ToolAuth implements ToolAuthorizationPort{allow=true;calls=0;async authorize(r:ToolRequest,o:{capability:string},hash:string):Promise<AuthorizationDecision>{this.calls++;return{allowed:this.allow,authorizationReference:"j08-auth",bindingHash:hash,capability:o.capability,resource:r.resource,expiresAt:Date.now()+10_000,emergencyEpoch:1,reason:"j0.3"};}async revalidate(){return this.allow;}}
const broker:CredentialBroker={lease:async()=>undefined};

describe("J0.8 A-T acceptance",()=>{
 it("J0.8-A — Protected baseline",()=>{expect(readFileSync("tests/acceptance/j08-gates.json","utf8")).toContain("4c05f1d9522d4950e6f9b12a0087290ba74bd5fb");});
 it("J0.8-B — Canonical event contracts",async()=>{const x=system();expect((await x.sys.accept(event())).status).toBe("accepted");await expect(x.sys.accept(event({eventType:"unknown.event"}))).rejects.toThrow("EVENT_TYPE_UNKNOWN");});
 it("J0.8-D — Durable inbox and deduplication",async()=>{const x=system(),handle=vi.fn(async()=>{});x.router.subscribe(sub());x.router.registerConsumer({consumerId:"consumer-1",handle});const e=event();await x.sys.accept(e);await x.router.route(e);expect(handle).toHaveBeenCalledTimes(1);expect(x.evidence.events.some(v=>v.type==="EVENT_DEDUPLICATED")).toBe(true);});
 it("J0.8-E — Authenticated event ingress",async()=>{const x=system("external.test"),key="ingress-test-key",timestamp=Date.parse(now),rawBody=JSON.stringify({message:"hello"}),sourceEventId="provider-1",material=`${timestamp}.${sourceEventId}..${rawBody}`,signature=createHmac("sha256",key).update(material).digest("hex"),ingress=new ExternalEventIngress(x.sys,new Map([["provider",{producerId:"provider",ownerId:owner,projectId:project,eventType:"external.test",schemaVersion:1,subject:"external",classification:"D1",privacy:"private-cloud"}]]),new HmacIngressAuthenticator(async()=>key,300_000,()=>timestamp),new MemoryIngressReceipts(),x.evidence);expect((await ingress.ingest({producerId:"provider",sourceEventId,timestamp,signature,rawBody})).status).toBe("accepted");await expect(ingress.ingest({producerId:"provider",sourceEventId,timestamp,signature,rawBody})).rejects.toThrow("INGRESS_REPLAY");});
 it("J0.8-F — Owner/project isolation",async()=>{const x=system(),handle=vi.fn(async()=>{});x.router.subscribe(sub());x.router.registerConsumer({consumerId:"consumer-1",handle});await x.sys.accept(event({ownerId:"other-owner"}));await x.sys.accept(event({projectId:"other-project"}));expect(handle).not.toHaveBeenCalled();});
 it("J0.8-G — Privacy and classification",async()=>{const x=system(),handle=vi.fn(async()=>{});x.router.subscribe(sub({boundary:"EXTERNAL_SERVICE"}));x.router.registerConsumer({consumerId:"consumer-1",handle});await x.sys.accept(event({privacy:"local-only",payloadClassification:"D4"}));expect(handle).not.toHaveBeenCalled();await expect(x.sys.accept(event({payloadClassification:"D5",privacy:"local-only"}))).rejects.toThrow();});
 it("J0.8-H — Subscription authorization",async()=>{const x=system(),handle=vi.fn(async()=>{});x.auth.allow=false;x.router.subscribe(sub());x.router.registerConsumer({consumerId:"consumer-1",handle});await x.sys.accept(event());expect(handle).not.toHaveBeenCalled();});
 it("J0.8-I — At-least-once safe delivery",async()=>{const x=system(),effect=vi.fn(async()=>{});x.router.subscribe(sub());x.router.registerConsumer({consumerId:"consumer-1",handle:effect});const e=event();await x.sys.accept(e);for(let i=0;i<5;i++)await x.router.route(e);expect(effect).toHaveBeenCalledTimes(1);});
 it("J0.8-J — Ordering and stale-event handling",async()=>{const x=system();await x.sys.accept(event({sequenceKey:"device:1",sequence:2}));await expect(x.sys.accept(event({sequenceKey:"device:1",sequence:1}))).rejects.toThrow("STALE_EVENT");});
 it("J0.8-K — Correlation, causation and loop protection",async()=>{const x=system();await expect(x.sys.accept(event({chainDepth:13}))).rejects.toThrow("EVENT_LOOP_DETECTED");const e=event({correlationId:"trace-chain"});await x.sys.accept(e);const replay=await x.sys.replay(e.eventId,"OWNER","recovery");expect(replay.event.causationId).toBe(e.eventId);expect(replay.event.correlationId).toBe("trace-chain");});
 it("J0.8-L — Retry classification and bounds",async()=>{const x=system(),handler=vi.fn(async()=>{throw new EventSystemError("TEMPORARY_DEPENDENCY");});x.router.subscribe(sub({maxAttempts:3}));x.router.registerConsumer({consumerId:"consumer-1",handle:handler});await x.sys.accept(event());expect(handler).toHaveBeenCalledTimes(3);expect(x.store.dead).toHaveLength(1);});
 it("J0.8-M — Durable dead-letter handling",async()=>{const x=system();x.router.subscribe(sub({maxAttempts:2}));x.router.registerConsumer({consumerId:"consumer-1",handle:async()=>{throw new EventSystemError("POLICY_DENIED");}});await x.sys.accept(event());expect(x.store.dead[0]?.code).toBe("POLICY_DENIED");expect(x.store.dead[0]?.attempts).toBe(1);});
 it("J0.8-N — Controlled replay",async()=>{const x=system(),e=event();await x.sys.accept(e);await expect(x.sys.replay(e.eventId,"OTHER","attack")).rejects.toThrow("REPLAY_UNAUTHORIZED");const replay=await x.sys.replay(e.eventId,"OWNER","repair");expect(replay.event.replayOf).toBe(e.eventId);expect(replay.event.eventId).not.toBe(e.eventId);});
 it("J0.8-O — Durable scheduling",async()=>{const x=system(),schedule:EventSchedule={scheduleId:"daily",ownerId:owner,projectId:project,eventType:"system.test",schemaVersion:1,subject:"due",payload:{scheduled:true},classification:"D1",privacy:"private-cloud",timezone:"Europe/Berlin",nextDueAt:now,intervalSeconds:3600,enabled:true,occurrence:0};await x.store.saveSchedule(schedule);const scheduler=new EventScheduler(x.sys,x.store);expect((await scheduler.tick(new Date(now))).length).toBe(1);expect((await scheduler.tick(new Date(now))).length).toBe(0);});
 it("J0.8-P — J0.3 security preservation",async()=>{const x=system("security.approval.granted");let authority=false;x.router.subscribe(sub({eventType:"security.approval.granted"}));x.router.registerConsumer({consumerId:"consumer-1",handle:async()=>{authority=false;}});await x.sys.accept(event({eventType:"security.approval.granted",payload:{approved:true,authorization:"forged"}}));expect(authority).toBe(false);});
 it("J0.8-Q — J0.7 gateway enforcement",async()=>{const adapter=new SyntheticToolAdapter("read"),tool=syntheticTool("mock.read","read",{},adapter),auth=new ToolAuth(),gateway=new UniversalToolGateway(new UniversalToolRegistry([tool]),auth,broker,{append:async()=>{}}),consumer=new GovernedEventToolConsumer("consumer-1",gateway,e=>({requestId:`tool-${e.eventId}`,correlationId:e.correlationId,actor:{ownerId:owner,actorId:owner,role:"OWNER"},projectId:project,source:"SYSTEM",toolId:"mock.read",toolVersion:1,operation:"run",input:{key:"event",value:e.eventId},resource:"jarvis",privacyClass:"D0",requestedMode:"EXECUTE",deadlineEpochMs:Date.now()+5000,maxCostMinor:10,metadata:{}}));auth.allow=false;await expect(consumer.handle(event())).rejects.toThrow("AUTHORIZATION_INVALID");expect(adapter.calls).toBe(0);expect(auth.calls).toBe(1);});
 it("J0.8-S — Safe evidence and owner control",async()=>{const x=system();x.router.subscribe(sub());x.router.setEnabled("sub-1",false);expect(x.router.inspect()[0]?.enabled).toBe(false);expect(JSON.stringify(safeEventMetadata({token:"secret",ok:"visible"}))).toBe('{"ok":"visible"}');expect(await x.sys.health()).toMatchObject({eventTypes:1,subscriptions:1});});
 it("J0.8-T — Full event-system integration",async()=>{const x=system(),effect=vi.fn(async()=>{});x.router.subscribe(sub());x.router.registerConsumer({consumerId:"consumer-1",handle:effect});const accepted=await x.sys.accept(event({correlationId:"full-chain"}));expect(accepted.status).toBe("accepted");expect(effect).toHaveBeenCalledOnce();expect(x.evidence.events.map(v=>v.type)).toEqual(expect.arrayContaining(["EVENT_ACCEPTED","EVENT_ROUTED","EVENT_PROCESSING_STARTED","EVENT_PROCESSING_COMPLETED"]));});
});
