import { describe,expect,it } from "vitest";
import { randomUUID } from "node:crypto";import { mkdtemp,readFile,rm } from "node:fs/promises";import { tmpdir } from "node:os";import { join } from "node:path";
import { AuditRecordV3Schema,BoundedTelemetryBuffer,CostObservability,MetricsRegistry,StructuredLocalTelemetryExporter,assertNoSecretLikeMaterial,canonicalize,materializeAuditRecord,safeText,verifyAuditChain,type AuditRecordDraft,type TelemetryExporter } from "@jarvis/audit";
import { J09AccountabilityBridge } from "@jarvis/core";
const draft=():AuditRecordDraft=>({auditId:randomUUID(),occurredAt:"2026-09-03T16:00:00.000Z",ownerId:"owner",projectId:"p",actor:{id:"core",type:"CORE"},action:"system.started",target:{type:"system"},result:"SUCCESS",severity:"INFO",classification:"D0",trace:{traceId:"trace",spanId:"span",correlationId:"corr"},redactions:[],retentionClass:"SECURITY",safeMetadata:{}});
describe("J0.9 hardening",()=>{
 it("detects changed and missing audit chain records",()=>{const a=materializeAuditRecord(draft(),1,"2026-09-03T16:00:00.000Z",null),b=materializeAuditRecord({...draft(),action:"system.stopped"},2,"2026-09-03T16:00:01.000Z",a.recordHash),c=materializeAuditRecord({...draft(),action:"system.started"},3,"2026-09-03T16:00:02.000Z",b.recordHash);expect(verifyAuditChain([a,{...b,result:"FAILED"}])).toMatchObject({ok:false,reason:"RECORD_HASH_MISMATCH"});expect(verifyAuditChain([a,c])).toMatchObject({ok:false,reason:"SEQUENCE_GAP"});expect(verifyAuditChain([c],{previousHash:b.recordHash,previousSequence:2})).toMatchObject({ok:true,lastSequence:3});});
 it("rejects malformed, unknown and D5 audit records",()=>{const valid=materializeAuditRecord(draft(),1,"2026-09-03T16:00:00.000Z",null);expect(()=>AuditRecordV3Schema.parse({...valid,action:"unknown.action"})).toThrow();expect(()=>AuditRecordV3Schema.parse({...valid,classification:"D5"})).toThrow();});
 it("rejects plaintext secret-like authoritative content",()=>{expect(()=>assertNoSecretLikeMaterial({password:"p@ss"})).toThrow("SECRET_MATERIAL_DENIED");expect(()=>assertNoSecretLikeMaterial({authorization:"Bearer abc.def"})).toThrow("SECRET_MATERIAL_DENIED");});
 it("canonicalization is deterministic and rejects non-finite numbers",()=>{expect(canonicalize({z:[2,1],a:{b:true,a:false}})).toBe(canonicalize({a:{a:false,b:true},z:[2,1]}));expect(()=>canonicalize(Number.NaN)).toThrow("NON_FINITE_CANONICAL_NUMBER");});
 it("sanitizes log injection control characters",()=>{expect(safeText("ok\r\nFORGED")).toBe("ok  FORGED");});
 it("bounds metric cardinality, cost dimensions and high-cardinality identifiers",()=>{const m=new MetricsRegistry(4),cost=new CostObservability(m);m.inc("a",{subsystem:"core"});cost.model("actual",12,"external");cost.tool("estimated",3,"write");expect(()=>m.inc("bad",{email:"owner@example.com"})).toThrow("UNBOUNDED_METRIC_LABEL");expect(Object.keys(m.snapshot().histograms)).toHaveLength(2);});
 it("exporter outage cannot grow telemetry without bound",async()=>{const failing:TelemetryExporter={export:async()=>{throw new Error("down")}},buffer=new BoundedTelemetryBuffer(failing,3,2);buffer.enqueue(1);buffer.enqueue(2);buffer.enqueue(3);expect(buffer.enqueue(4)).toBe(false);await buffer.flush();expect(buffer.size).toBe(3);});
 it("structured local exporter is bounded and refuses secrets",async()=>{const dir=await mkdtemp(join(tmpdir(),"jarvis-j09-")),file=join(dir,"telemetry.jsonl"),exporter=new StructuredLocalTelemetryExporter(file,1024);try{await exporter.export([{level:"INFO",message:"safe"}]);expect(await readFile(file,"utf8")).toContain('"safe"');await expect(exporter.export([{password:"never"}])).rejects.toThrow("SECRET_MATERIAL_DENIED");}finally{await rm(dir,{recursive:true,force:true});}});
 it("models and tools cannot fabricate audit authority by schema or bridge",async()=>{const valid=materializeAuditRecord(draft(),1,"2026-09-03T16:00:00.000Z",null);expect(()=>AuditRecordV3Schema.parse({...valid,actor:{id:"model",type:"MODEL"}})).toThrow();expect(()=>AuditRecordV3Schema.parse({...valid,action:"audit.admin.granted"})).toThrow();const bridge=new J09AccountabilityBridge({append:async()=>({})});await expect(bridge.record({ownerId:"owner",projectId:"p",actorId:"tool",actorType:"TOOL",action:"security.approval.granted",result:"SUCCESS",classification:"D1",correlationId:"corr",traceId:"trace",targetType:"approval"})).rejects.toThrow("AUDIT_AUTHORITY_CONFUSION_DENIED");});
});
