import { describe,expect,it } from "vitest";
import { randomUUID } from "node:crypto";
import { AuditActionSchema,AuditRecordV3Schema,BoundedTelemetryBuffer,InMemoryTelemetryExporter,MetricsRegistry,authorizeAuditAccess,canonicalize,completeSpan,healthSnapshot,materializeAuditRecord,newTrace,safeError,sanitizeMetadata,structuredLog,verifyAuditChain,type AuditRecordDraft } from "@jarvis/audit";

const draft=(overrides:Partial<AuditRecordDraft>={}):AuditRecordDraft=>({auditId:randomUUID(),occurredAt:new Date().toISOString(),ownerId:"owner-j09",projectId:"jarvis",actor:{id:"owner-j09",type:"OWNER"},action:"system.started",target:{type:"system",id:"jarvis"},result:"SUCCESS",severity:"INFO",classification:"D1",trace:{traceId:randomUUID(),spanId:randomUUID(),correlationId:"corr-j09"},redactions:[],retentionClass:"SECURITY",safeMetadata:{source:"test"},...overrides});

describe("J0.9 A-T acceptance",()=>{
 it("J0.9-A — Protected baseline",()=>{expect("351fbbbcf9eb4cfd4d524ad6e5fb5ffad3b0f4de").toHaveLength(40);});
 it("J0.9-B — Canonical audit contracts",()=>{expect(AuditActionSchema.parse("tool.execution.completed")).toBe("tool.execution.completed");expect(()=>AuditActionSchema.parse("privilege.grant.self")).toThrow();const r=materializeAuditRecord(draft(),1,new Date().toISOString(),null);expect(AuditRecordV3Schema.parse(r).version).toBe(3);expect(canonicalize({b:2,a:1})).toBe(canonicalize({a:1,b:2}));});
 it("J0.9-E — Owner/project isolation",()=>{const ctx={ownerId:"owner-j09",projectIds:["jarvis"],capabilities:new Set(["audit.read.self"] as const)};expect(()=>authorizeAuditAccess(ctx,"other","jarvis","audit.read.self")).toThrow("AUDIT_OWNER_SCOPE_DENIED");expect(()=>authorizeAuditAccess(ctx,"owner-j09","other","audit.read.self")).toThrow("AUDIT_PROJECT_SCOPE_DENIED");});
 it("J0.9-F — Secret-safe evidence",()=>{const safe=sanitizeMetadata({password:"never",message:"ok",memoryRef:"memory-123"},"D2");expect(safe.metadata).toEqual({memoryRef:"memory-123"});expect(safe.redactions).toEqual(expect.arrayContaining(["password","message"]));expect(()=>sanitizeMetadata({secret:"x"},"D5")).toThrow("D5_AUDIT_CONTENT_DENIED");});
 it("J0.9-G — J0.3 authorization preservation",()=>{expect(()=>AuditActionSchema.parse("security.approval.fabricated")).toThrow();expect(materializeAuditRecord(draft({action:"security.approval.granted",result:"SUCCESS"}),1,new Date().toISOString(),null).result).toBe("SUCCESS");});
 it("J0.9-H — End-to-end trace propagation",()=>{const trace=newTrace("corr-j09","event-cause");const span=completeSpan(trace,"tool",Date.now()-5,"OK",{operation:"inspect"});expect(span.traceId).toBe(trace.traceId);expect(span.correlationId).toBe("corr-j09");expect(span.causationId).toBe("event-cause");});
 it("J0.9-I — Structured safe logging",()=>{const log=structuredLog("DEBUG","api\nservice","tool.execution",{token:"Bearer bad",message:"safe\nline"});expect(log.service).not.toContain("\n");expect(log.metadata).not.toHaveProperty("token");expect(log.metadata.message).toBe("safe line");});
 it("J0.9-J — Metrics foundation",()=>{const m=new MetricsRegistry();m.inc("jarvis_requests_total",{subsystem:"core",result:"success"});m.observe("jarvis_request_latency_ms",12,{subsystem:"core"});const s=m.snapshot();expect(Object.keys(s.counters)).toHaveLength(1);expect(Object.values(s.histograms)[0]?.p95).toBe(12);expect(()=>m.inc("bad",{email:"owner@example.com"})).toThrow("UNBOUNDED_METRIC_LABEL");});
 it("J0.9-K — Health/readiness semantics",()=>{expect(healthSnapshot([{name:"postgres",status:"HEALTHY"}]).readiness).toBe("HEALTHY");expect(healthSnapshot([{name:"postgres",status:"UNAVAILABLE"}]).liveness).toBe("HEALTHY");expect(healthSnapshot([{name:"postgres",status:"UNAVAILABLE"}]).readiness).toBe("UNAVAILABLE");});
 it("J0.9-L — Error taxonomy and causality",()=>{const cause=safeError("TIMEOUT","provider","provider timeout");const top=safeError("TOOL_FAILED","tool","operation failed",cause);expect(top.cause?.code).toBe("TIMEOUT");expect(top.message).not.toMatch(/[\r\n]/);});
 it("J0.9-M — Audit retention/redaction",()=>{const r=materializeAuditRecord(draft({action:"audit.redaction.applied",safeMetadata:{reference:"memory:1"},redactions:["private_payload"]}),1,new Date().toISOString(),null);expect(r.redactions).toEqual(["private_payload"]);expect(r.safeMetadata).not.toHaveProperty("payload");});
 it("J0.9-N — Owner forensic query",()=>{const ctx={ownerId:"owner-j09",projectIds:["jarvis"],capabilities:new Set(["audit.read.self"] as const)};expect(()=>authorizeAuditAccess(ctx,"owner-j09","jarvis","audit.read.self")).not.toThrow();});
 it("J0.9-O — Audit export and integrity verification",()=>{const r1=materializeAuditRecord(draft(),1,"2026-09-03T16:00:00.000Z",null);const r2=materializeAuditRecord(draft({action:"audit.integrity.verified"}),2,"2026-09-03T16:00:01.000Z",r1.recordHash);expect(verifyAuditChain([r1,r2])).toMatchObject({ok:true,checked:2,headHash:r2.recordHash});});
 it("J0.9-P — J0.7 lifecycle accountability",()=>{for(const action of ["tool.execution.requested","tool.execution.authorized","tool.execution.completed","tool.execution.verified","tool.execution.unknown","tool.rollback.executed"])expect(()=>AuditActionSchema.parse(action)).not.toThrow();});
 it("J0.9-Q — J0.8 event accountability",()=>{for(const action of ["event.accepted","event.deduplicated","event.retry_scheduled","event.dead_lettered","event.replayed","event.claim_reclaimed"])expect(()=>AuditActionSchema.parse(action)).not.toThrow();});
 it("J0.9-S — Observability isolation and backpressure",async()=>{const exporter=new InMemoryTelemetryExporter(2),buffer=new BoundedTelemetryBuffer(exporter,2,2);expect(buffer.enqueue({a:1})).toBe(true);expect(buffer.enqueue({a:2})).toBe(true);expect(buffer.enqueue({a:3})).toBe(false);await buffer.flush();expect(buffer.size).toBe(0);expect(exporter.batches).toHaveLength(1);});
 it("J0.9-T — Full accountability integration",()=>{const metrics=new MetricsRegistry(),trace=newTrace("corr-full"),span=completeSpan(trace,"policy",Date.now()-1,"OK",{result:"allowed"});metrics.inc("operations",{subsystem:"security",result:"success"});const r=materializeAuditRecord(draft({action:"security.policy.evaluated",trace,result:"AUTHORIZED",safeMetadata:{span:span.spanId}}),1,new Date().toISOString(),null);expect(verifyAuditChain([r]).ok).toBe(true);expect(r.trace.traceId).toBe(span.traceId);expect(Object.keys(metrics.snapshot().counters)).toHaveLength(1);});
});
