import { describe,expect,it } from "vitest";
import { randomBytes,randomUUID } from "node:crypto";
import { GovernanceStateSchema,RecordCipher } from "@jarvis/security";
import { HmacRecoveryAuthenticator,RecoveryObligationSigner,recoveryObligationDigest,sanitizeRecoveredGovernancePayload } from "@jarvis/storage";

const owner="owner-j10-hardening",hash="a".repeat(64),backupId=randomUUID();
describe("J0.10 recovery hardening",()=>{
 it("authenticates the whole sovereign recovery package with separate owner-controlled key material",()=>{const key=randomBytes(32),auth=new HmacRecoveryAuthenticator(key,"recovery-key-v1"),payload={version:1 as const,ownerId:owner,backupId,manifestDigest:hash,baseDigest:hash,supplementDigest:hash,obligationDigest:hash},seal=auth.seal(payload);expect(auth.verify(seal,owner).payload).toEqual(payload);expect(()=>auth.verify({...seal,payload:{...payload,supplementDigest:"b".repeat(64)}},owner)).toThrow("RECOVERY_AUTHENTICITY_FAILED");const wrong=new HmacRecoveryAuthenticator(randomBytes(32),"recovery-key-v1");expect(()=>wrong.verify(seal,owner)).toThrow("RECOVERY_AUTHENTICITY_FAILED");expect(JSON.stringify(seal)).not.toContain(key.toString("hex"));auth.destroy();wrong.destroy();});
 it("binds authoritative deletion and revocation obligations against tampering",()=>{const signer=new RecoveryObligationSigner(randomBytes(32),"recovery-obligations-v1"),payload={version:1 as const,ownerId:owner,generation:4,createdAt:1800000000000,revokedDeviceIds:["device-revoked"],revokedSubjectIds:["agent-revoked"],deletedRecordIds:[randomUUID()],removedDelegationIds:["delegation-removed"]},signed=signer.sign(payload);expect(signer.verify(signed,owner).digest).toBe(recoveryObligationDigest(payload));expect(()=>signer.verify({...signed,payload:{...payload,generation:5}},owner)).toThrow("RECOVERY_OBLIGATION_INTEGRITY_FAILED");expect(()=>signer.verify(signed,"other-owner")).toThrow("RECOVERY_OBLIGATION_INTEGRITY_FAILED");signer.destroy();});
 it("preserves owner policy and emergency controls while invalidating executable authority",()=>{const cipher=new RecordCipher(randomBytes(32)),state=GovernanceStateSchema.parse({version:1,ownerId:owner,controls:{version:1,epoch:8,flags:["SECURITY_LOCKDOWN","EXTERNAL_ACTIONS_DISABLED"],frozenActors:["agent-frozen"]},policies:[],budgets:{"agent-frozen":{version:1,actorId:"agent-frozen",maximumRuntimeMs:1000,maximumSpendMinor:0,spentMinor:0,maximumToolCalls:1,toolCalls:0,maximumRisk:"R1",resources:["owner-data"],environments:["development"],startedAt:1,notBefore:0,expiresAt:9999999999999,networkAllowed:false,maximumConcurrent:1,approvalThreshold:"R1"}},approvals:{},authorizations:{},requests:{},riskRules:["AUTO_ALLOW","ALLOW_WITH_AUDIT","ALLOW_WITH_AUDIT","REQUEST_APPROVAL","REQUEST_APPROVAL_AND_STEP_UP_AUTH","DENY"]}),encrypted=cipher.encrypt(state,"security:development:governance:v1"),restored=GovernanceStateSchema.parse(cipher.decrypt(sanitizeRecoveredGovernancePayload(encrypted,cipher,owner),"security:development:governance:v1"));expect(restored.ownerId).toBe(owner);expect(restored.controls.flags).toEqual(state.controls.flags);expect(restored.controls.frozenActors).toEqual(state.controls.frozenActors);expect(restored.controls.epoch).toBe(9);expect(restored.policies).toEqual(state.policies);expect(restored.riskRules).toEqual(state.riskRules);expect(restored.budgets).toEqual({});expect(restored.approvals).toEqual({});expect(restored.authorizations).toEqual({});expect(restored.requests).toEqual({});});
});
